//! Story 1.3 — gen_ts per-target generator.
//!
//! Emits TypeScript type declarations for the DreamBall root
//! protocol surface to `src/lib/generated/types.ts`. The canonical
//! body is byte-equivalent to the legacy static-text generator
//! (deleted in Story 1.5 cutover per D-030 Option A).
//!
//! Spike findings (docs/decisions/2026-04-28-codegen-spike-findings.md)
//! show JSON Schema 2020-12 + the small `x-` extension vocabulary is
//! sufficient to drive this output structurally — that wiring lands
//! incrementally after Story 1.4's byte-equivalence gate is green.

const std = @import("std");
const main_mod = @import("main.zig");
const cc = @import("codegen_common");

const OUT_PATH = "src/lib/generated/types.ts";
const ARCHIFORM_OUT_PATH = "src/lib/generated/memory-palace.types.ts";

pub fn generate(ctx: *const main_mod.GeneratorCtx) !void {
    try ctx.writeOutput(OUT_PATH, BODY, .ts);
}

/// Per-archiform pass (Story 2.2 AC1): emits Memory Palace TS type
/// extensions to `src/lib/generated/memory-palace.types.ts`.
/// Names avoid collision with root types (e.g. MemoryPalaceInscription
/// vs root Inscription, MemoryPalaceTriple vs root Triple).
pub fn generateArchiform(actx: *const cc.ArchiformCtx) !void {
    // Build archiform TS header naming the memory-palace schema as source.
    const header = try std.fmt.allocPrint(
        actx.arena,
        \\// DO NOT EDIT — generated by tools/schema-gen.
        \\// Provenance:
        \\//   source-schema:     {0s}
        \\//   source-schema-fp:  blake3:{1s}
        \\//   schema-version:    {2s}
        \\//   generator-id:      {3s}
        \\//   generator-commit:  {4s}
        \\// Regenerate via `bun run codegen`. Hand-edits will be overwritten.
        \\// See docs/decisions/2026-04-25-json-schema-canonical.md (D-018) and
        \\// docs/sprints/002-archiform-foundation/architecture-decisions.md (D-030).
        \\
        \\
    ,
        .{
            actx.schema_path,
            actx.schema_fp,
            actx.schema_version,
            actx.generator_id,
            actx.generator_commit,
        },
    );

    var file = try std.Io.Dir.cwd().createFile(actx.io, ARCHIFORM_OUT_PATH, .{ .truncate = true });
    defer file.close(actx.io);
    var file_buf: [4096]u8 = undefined;
    var fw = file.writer(actx.io, &file_buf);
    try fw.interface.writeAll(header);
    try fw.interface.writeAll(ARCHIFORM_BODY);
    try fw.interface.flush();

    try main_mod.logKVPub(actx.stderr, .{
        .{ "phase", "output-written" },
        .{ "path", ARCHIFORM_OUT_PATH },
        .{ "bytes", header.len + ARCHIFORM_BODY.len },
        .{ "pass", "per-archiform" },
    });
}

const ARCHIFORM_BODY =
    \\// Memory Palace archiform TypeScript type extensions.
    \\// These extend the root types in ./types.ts for the Memory Palace archiform.
    \\// Names are prefixed with MemoryPalace to avoid collision with root types.
    \\// Source: schemas/memory-palace-0.1.0.json (D-018, D-017).
    \\
    \\/** Memory Palace palace node (KuzuDB). */
    \\export interface MemoryPalacePalaceNode {
    \\  fp: string;
    \\  created_at?: number | null;
    \\  mythos_head_fp?: string | null;
    \\  guild_fps: string[];
    \\  archiform_fp?: string | null;
    \\}
    \\
    \\/** Memory Palace room node (KuzuDB). */
    \\export interface MemoryPalaceRoomNode {
    \\  fp: string;
    \\  created_at?: number | null;
    \\}
    \\
    \\/** Memory Palace inscription node (KuzuDB). */
    \\export interface MemoryPalaceInscriptionNode {
    \\  fp: string;
    \\  source_blake3?: string | null;
    \\  orphaned: boolean;
    \\  embedding?: number[] | null;
    \\  created_at?: number | null;
    \\  policy: string;
    \\  revision: number;
    \\  surface?: string | null;
    \\  placement?: string | null;
    \\}
    \\
    \\/** Memory Palace agent node (KuzuDB). D-028: knowledge graph via Triple nodes. */
    \\export interface MemoryPalaceAgentNode {
    \\  fp: string;
    \\  created_at?: number | null;
    \\  personality_master_prompt: string;
    \\  memory: string;
    \\  emotional_register: string;
    \\  interaction_set: string;
    \\}
    \\
    \\/** Memory Palace triple node (KuzuDB). D-028: native KG triple row. */
    \\export interface MemoryPalaceTripleNode {
    \\  fp: string;
    \\  agent_fp: string;
    \\  subject: string;
    \\  predicate: string;
    \\  object: string;
    \\  created_at?: number | null;
    \\}
    \\
    \\/** Memory Palace mythos node (KuzuDB). */
    \\export interface MemoryPalaceMythosNode {
    \\  fp: string;
    \\  body?: string | null;
    \\  canonicality?: string | null;
    \\  discovered_in_action_fp?: string | null;
    \\  created_at?: number | null;
    \\}
    \\
    \\/** Memory Palace aqueduct node (KuzuDB). */
    \\export interface MemoryPalaceAqueductNode {
    \\  fp: string;
    \\  from_fp: string;
    \\  to_fp: string;
    \\  resistance: number;
    \\  capacitance: number;
    \\  strength: number;
    \\  conductance: number;
    \\  phase: string;
    \\  revision: number;
    \\  last_traversal_ts: number;
    \\}
    \\
    \\/** Memory Palace action log node (KuzuDB). D-021: logical commit record. */
    \\export interface MemoryPalaceActionLogNode {
    \\  fp: string;
    \\  palace_fp: string;
    \\  action_kind: string;
    \\  actor_fp: string;
    \\  target_fp?: string | null;
    \\  parent_hashes: string[];
    \\  timestamp?: number | null;
    \\  cbor_bytes_blake3?: string | null;
    \\}
    \\
;

const BODY =
    \\// Types mirror the Zig protocol surface in src/protocol.zig +
    \\// src/protocol_v2.zig. The CBOR wire format is specified in
    \\// docs/PROTOCOL.md; the matching encoder/decoder lives in
    \\// ./cbor.ts.
    \\
    \\export type Base58 = `b58:${string}`;
    \\export type Fingerprint = Base58;    // 32 bytes, base58-encoded with "b58:" prefix
    \\export type Bytes32 = Base58;         // same shape; different semantic label
    \\
    \\export type DreamBallType =
    \\  | 'avatar'
    \\  | 'agent'
    \\  | 'tool'
    \\  | 'relic'
    \\  | 'field'
    \\  | 'guild';
    \\
    \\export type Stage = 'seed' | 'dreamball' | 'dragonball';
    \\
    \\export interface Signature {
    \\  alg: 'ed25519' | 'ml-dsa-87';
    \\  value: Base58;
    \\}
    \\
    \\export interface Asset {
    \\  'media-type': string;
    \\  hash: Bytes32;
    \\  url?: string[];
    \\  embedded?: Base58;
    \\  size?: number;
    \\  note?: string;
    \\}
    \\
    \\export interface Look {
    \\  asset?: Asset[];
    \\  preview?: Asset;
    \\  background?: string;
    \\  note?: string;
    \\}
    \\
    \\export interface Feel {
    \\  personality?: string;
    \\  voice?: string;
    \\  values?: string[];
    \\  tempo?: string;
    \\  note?: string;
    \\}
    \\
    \\export interface Skill {
    \\  name: string;
    \\  trigger?: string;
    \\  body?: string;
    \\  asset?: Asset;
    \\  requires?: string[];
    \\  note?: string;
    \\}
    \\
    \\export interface Act {
    \\  model?: string;
    \\  'system-prompt'?: string;
    \\  skill?: Skill[];
    \\  script?: Asset[];
    \\  tool?: string[];
    \\  note?: string;
    \\}
    \\
    \\// ===== v2 =====
    \\
    \\export interface MemoryNode {
    \\  id: number;
    \\  content?: string;
    \\  lookups?: Record<string, number>;
    \\  created?: string;       // RFC 3339
    \\  'last-recalled'?: string;
    \\}
    \\
    \\export type MemoryConnectionKind = 'semantic' | 'emotional' | 'temporal' | 'other';
    \\
    \\export interface MemoryConnection {
    \\  from: number;
    \\  to: number;
    \\  kind: MemoryConnectionKind;
    \\  strength?: number;
    \\  label?: string;
    \\}
    \\
    \\export interface Memory {
    \\  nodes: MemoryNode[];
    \\  connections: MemoryConnection[];
    \\  'last-updated'?: string;
    \\}
    \\
    \\export interface Triple {
    \\  from: string;
    \\  label: string;
    \\  to: string;
    \\}
    \\
    \\export interface KnowledgeGraph {
    \\  triples: Triple[];
    \\  source?: string;
    \\}
    \\
    \\export interface EmotionalAxis {
    \\  name: string;
    \\  value: number;
    \\  min?: number;
    \\  max?: number;
    \\}
    \\
    \\export interface EmotionalRegister {
    \\  axes: EmotionalAxis[];
    \\  'observed-at'?: string;
    \\}
    \\
    \\export type InteractionKind = 'speak' | 'listen' | 'act' | 'receive';
    \\
    \\export interface Interaction {
    \\  turn: number;
    \\  actor: Fingerprint;
    \\  kind: InteractionKind;
    \\  content?: string;
    \\  timestamp?: string;
    \\  outcome?: string;
    \\}
    \\
    \\export interface InteractionSet {
    \\  'set-id': Base58;
    \\  interactions: Interaction[];
    \\  created?: string;
    \\}
    \\
    \\export interface GuildPolicy {
    \\  public: string[];
    \\  'guild-only': string[];
    \\  'admin-only': string[];
    \\  note?: string;
    \\}
    \\
    \\export interface GuildMembership {
    \\  member: Fingerprint;
    \\  'is-admin'?: boolean;
    \\}
    \\
    \\export interface Guild {
    \\  'guild-name': string;
    \\  'keyspace-root-hash': Bytes32;
    \\  members: GuildMembership[];
    \\  policy?: GuildPolicy;
    \\}
    \\
    \\export interface Relic {
    \\  'sealed-payload-hash': Bytes32;
    \\  'unlock-guild': Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\}
    \\
    \\export interface Transmission {
    \\  'tool-fp': Fingerprint;
    \\  'target-fp': Fingerprint;
    \\  'via-guild': Fingerprint;
    \\  'sender-fp'?: Fingerprint;
    \\  'transmitted-at'?: string;
    \\  'tool-envelope': Base58;   // raw CBOR bytes, base58-wrapped
    \\  signatures?: Signature[];
    \\}
    \\
    \\export interface SecretRef {
    \\  name: string;
    \\  locator: string;
    \\  'issued-by'?: Fingerprint;
    \\  description?: string;
    \\}
    \\
    \\// ===== The top-level DreamBall =====
    \\
    \\export interface DreamBall {
    \\  type: 'ball.dreamball' | `ball.dreamball.${DreamBallType}`;
    \\  'format-version': 1 | 2;
    \\  stage: Stage;
    \\  identity: Fingerprint;       // the Ed25519 pubkey in b58
    \\  'genesis-hash': Bytes32;
    \\  revision: number;
    \\  name?: string;
    \\  created?: string;
    \\  updated?: string;
    \\  note?: string;
    \\  look?: Look;
    \\  feel?: Feel;
    \\  act?: Act;
    \\  memory?: Memory;
    \\  'knowledge-graph'?: KnowledgeGraph;
    \\  'emotional-register'?: EmotionalRegister;
    \\  'interaction-set'?: InteractionSet[];
    \\  guild?: Fingerprint[];        // Guild memberships
    \\  contains?: Fingerprint[];
    \\  'derived-from'?: Fingerprint[];
    \\  signatures?: Signature[];
    \\  // Guild-type specific
    \\  'guild-name'?: string;
    \\  'keyspace-root-hash'?: Bytes32;
    \\  member?: Fingerprint[];
    \\  admin?: Fingerprint[];
    \\  policy?: GuildPolicy;
    \\  // Relic-type specific
    \\  'sealed-payload-hash'?: Bytes32;
    \\  'unlock-guild'?: Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\  // Tool-type specific
    \\  skill?: Skill;
    \\  'applicable-to'?: string[];
    \\  // Field-type specific
    \\  'omnispherical-grid'?: OmnisphericalGrid;
    \\  'ambient-palette'?: string[];
    \\  'dream-field-id'?: string;
    \\  // FR5 / Story 2.3 — genesis archiform binding (D-017). Optional 32-byte
    \\  // blake3 of the archiform schema body, immutable for the ball's lifetime.
    \\  // Sprint-001 envelopes lacking this field decode by implicitly binding to
    \\  // dreamball/memory-palace@0.1.0 (see src/lib/parse.ts).
    \\  'archiform-fp'?: Bytes32;
    \\  // Agent-type specific
    \\  'personality-master-prompt'?: string;
    \\  secret?: SecretRef[];
    \\}
    \\
    \\export interface Vec3 {
    \\  x: number;
    \\  y: number;
    \\  z: number;
    \\}
    \\
    \\export interface CameraRing {
    \\  radius: number;
    \\  tilt: number;
    \\  fov: number;
    \\}
    \\
    \\export interface OmnisphericalGrid {
    \\  'pole-north'?: Vec3;
    \\  'pole-south'?: Vec3;
    \\  'camera-ring'?: CameraRing[];
    \\  'layer-depth'?: number;
    \\  resolution?: number;
    \\  note?: string;
    \\}
    \\
    \\/** Convenience: a DreamBall bundle (the .jelly file) — the envelope
    \\ *  plus optional attachments carried alongside (textures, scripts,
    \\ *  sealed payloads). For most consumers `DreamBall` alone is enough.
    \\ */
    \\export interface DreamballBundle {
    \\  envelope: DreamBall;
    \\  attachments: Uint8Array[];
    \\  flags: {
    \\    compressed: boolean;
    \\    encrypted: boolean;
    \\    attachmentsEncrypted: boolean;
    \\  };
    \\  version: number;
    \\}
    \\
    \\export const FORMAT_VERSION = 1 as const;
    \\export const FORMAT_VERSION_V2 = 2 as const;
    \\
    \\export const DREAMBALL_TYPES: readonly DreamBallType[] = [
    \\  'avatar',
    \\  'agent',
    \\  'tool',
    \\  'relic',
    \\  'field',
    \\  'guild',
    \\] as const;
    \\
    \\// ===== §13 palace envelopes =====
    \\
    \\/** §13.1 field-kind open-enum attribute on ball.dreamball.field. */
    \\export interface FieldKind {
    \\  value: string;
    \\}
    \\
    \\/** §13.2 ball.layout — spatial arrangement of child DreamBalls. */
    \\export interface Placement {
    \\  'child-fp': Bytes32;
    \\  position: [number, number, number];
    \\  facing: [number, number, number, number];  // quaternion [qx, qy, qz, qw]
    \\}
    \\
    \\export interface Layout {
    \\  type: 'ball.layout';
    \\  'format-version': 2;
    \\  placements: Placement[];
    \\  note?: string;
    \\}
    \\
    \\/** §13.3 ball.timeline — DAG head-hashes for a palace. */
    \\export interface Timeline {
    \\  type: 'ball.timeline';
    \\  'format-version': 3;
    \\  'palace-fp': Bytes32;
    \\  'head-hashes': Bytes32[];
    \\  note?: string;
    \\}
    \\
    \\export type ActionKind =
    \\  | 'palace-minted'
    \\  | 'room-added'
    \\  | 'avatar-inscribed'
    \\  | 'aqueduct-created'
    \\  | 'move'
    \\  | 'true-naming'
    \\  | 'inscription-updated'
    \\  | 'inscription-orphaned'
    \\  | 'inscription-pending-embedding';
    \\
    \\/** §13.3 ball.action — a single DAG node in a palace timeline. */
    \\export interface Action {
    \\  type: 'ball.action';
    \\  'format-version': 3;
    \\  'action-kind': ActionKind;
    \\  actor: Bytes32;
    \\  'parent-hashes': Bytes32[];
    \\  'target-fp'?: Bytes32;
    \\  timestamp?: number;
    \\  deps?: Bytes32[];
    \\  nacks?: Bytes32[];
    \\}
    \\
    \\export type AqueductPhase = 'in' | 'out' | 'standing' | 'resonant';
    \\
    \\/** §13.4 ball.aqueduct — directed channel between two DreamBalls. */
    \\export interface Aqueduct {
    \\  type: 'ball.aqueduct';
    \\  'format-version': 2;
    \\  from: Bytes32;
    \\  to: Bytes32;
    \\  kind: string;   // open-enum: "gaze" | "visit" | "transmit" | …
    \\  capacity: number;
    \\  strength: number;
    \\  resistance: number;
    \\  capacitance: number;
    \\  conductance?: number;
    \\  phase?: AqueductPhase;
    \\  'last-traversed'?: number;
    \\}
    \\
    \\/** §13.5 ball.element-tag — elemental affinity attribute. */
    \\export interface ElementTag {
    \\  type: 'ball.element-tag';
    \\  'format-version': 2;
    \\  element: string;   // open-enum: "wood" | "fire" | "earth" | "metal" | "water" | …
    \\  phase?: string;    // open-enum: "nourishing" | "destruction" | "yin" | "yang" | …
    \\  note?: string;
    \\}
    \\
    \\/** §13.6 ball.trust-observation — multi-axis trust record. */
    \\export interface TrustAxis {
    \\  name: string;
    \\  value: number;
    \\  range: [number, number];
    \\}
    \\
    \\export interface TrustObservation {
    \\  type: 'ball.trust-observation';
    \\  'format-version': 2;
    \\  observer: Bytes32;
    \\  about: Bytes32;
    \\  axes?: TrustAxis[];
    \\  'observed-at'?: number;
    \\  context?: string;
    \\  signatures?: Signature[];
    \\}
    \\
    \\/** §13.7 ball.inscription — text/content attached to a room. */
    \\export interface Inscription {
    \\  type: 'ball.inscription';
    \\  'format-version': 2;
    \\  surface: string;     // open-enum: "scroll" | "tablet" | "book-spread" | "etched-wall" | …
    \\  placement: string;   // "auto" | "curator"
    \\  note?: string;
    \\}
    \\
    \\/** §13.8 ball.mythos — poetic or canonical naming chain. */
    \\export interface Mythos {
    \\  type: 'ball.mythos';
    \\  'format-version': 2;
    \\  'is-genesis': boolean;
    \\  predecessor?: Bytes32;
    \\  about?: Bytes32;
    \\  form?: string;      // open-enum: "blurb" | "invocation" | "image" | "utterance" | "glyph" | "true-name" | …
    \\  body?: string;
    \\  'true-name'?: string;
    \\  'discovered-in'?: Bytes32;
    \\  synthesizes?: Bytes32[];
    \\  'inspired-by'?: Bytes32[];
    \\  author?: Bytes32;
    \\  'authored-at'?: number;
    \\}
    \\
    \\/** §13.9 ball.archiform — room archetype/template. */
    \\export interface Archiform {
    \\  type: 'ball.archiform';
    \\  'format-version': 2;
    \\  form: string;        // open-enum: "library" | "forge" | "throne-room" | …
    \\  tradition?: string;  // open-enum: "hermetic" | "shinto" | "vedic" | "computational" | "none" | …
    \\  'parent-form'?: string;
    \\  note?: string;
    \\}
    \\
;
