//! Zig tool — emits TypeScript types + a minimal dCBOR encoder/decoder
//! matching the Zig side of the DreamBall protocol. Keeps the Svelte
//! library's wire-format knowledge in sync with the Zig protocol without
//! hand-maintaining duplicate schemas.
//!
//! Run from repo root:
//!   zig build schemagen
//! or
//!   bun run codegen
//!
//! Writes:
//!   src/lib/generated/types.ts
//!   src/lib/generated/cbor.ts
//!   src/lib/generated/README.md
//!
//! CLAUDE.md operating principle: the docs must explain WHY the generated
//! code is shaped the way it is — the generated README covers that.

const std = @import("std");

const TYPES_OUT = "src/lib/generated/types.ts";
const CBOR_OUT = "src/lib/generated/cbor.ts";
const README_OUT = "src/lib/generated/README.md";

const TYPES_SRC =
    \\// AUTO-GENERATED by tools/schema-gen — do not edit by hand.
    \\// Regenerate with `bun run codegen`.
    \\//
    \\// Types mirror the Zig protocol surface in src/protocol.zig +
    \\// src/protocol_v2.zig. The CBOR wire format is specified in
    \\// docs/PROTOCOL.md; the matching encoder/decoder lives in
    \\// ./cbor.ts.
    \\
    \\export type Base58 = `b58:${string}`;
    \\export type Fingerprint = Base58;    // 32 bytes, base58-encoded with "b58:" prefix
    \\export type Bytes32 = Base58;         // same shape; different semantic label
    \\
    \\export type DreamBallType =
    \\  | 'avatar'
    \\  | 'agent'
    \\  | 'tool'
    \\  | 'relic'
    \\  | 'field'
    \\  | 'guild';
    \\
    \\export type Stage = 'seed' | 'dreamball' | 'dragonball';
    \\
    \\export interface Signature {
    \\  alg: 'ed25519' | 'ml-dsa-87';
    \\  value: Base58;
    \\}
    \\
    \\export interface Asset {
    \\  'media-type': string;
    \\  hash: Bytes32;
    \\  url?: string[];
    \\  embedded?: Base58;
    \\  size?: number;
    \\  note?: string;
    \\}
    \\
    \\export interface Look {
    \\  asset?: Asset[];
    \\  preview?: Asset;
    \\  background?: string;
    \\  note?: string;
    \\}
    \\
    \\export interface Feel {
    \\  personality?: string;
    \\  voice?: string;
    \\  values?: string[];
    \\  tempo?: string;
    \\  note?: string;
    \\}
    \\
    \\export interface Skill {
    \\  name: string;
    \\  trigger?: string;
    \\  body?: string;
    \\  asset?: Asset;
    \\  requires?: string[];
    \\  note?: string;
    \\}
    \\
    \\export interface Act {
    \\  model?: string;
    \\  'system-prompt'?: string;
    \\  skill?: Skill[];
    \\  script?: Asset[];
    \\  tool?: string[];
    \\  note?: string;
    \\}
    \\
    \\// ===== v2 =====
    \\
    \\export interface MemoryNode {
    \\  id: number;
    \\  content?: string;
    \\  lookups?: Record<string, number>;
    \\  created?: string;       // RFC 3339
    \\  'last-recalled'?: string;
    \\}
    \\
    \\export type MemoryEdgeKind = 'semantic' | 'emotional' | 'temporal' | 'other';
    \\
    \\export interface MemoryEdge {
    \\  from: number;
    \\  to: number;
    \\  kind: MemoryEdgeKind;
    \\  strength?: number;
    \\  label?: string;
    \\}
    \\
    \\export interface Memory {
    \\  nodes: MemoryNode[];
    \\  edges: MemoryEdge[];
    \\  'last-updated'?: string;
    \\}
    \\
    \\export interface Triple {
    \\  subject: string;
    \\  predicate: string;
    \\  object: string;
    \\}
    \\
    \\export interface KnowledgeGraph {
    \\  triples: Triple[];
    \\  source?: string;
    \\}
    \\
    \\export interface EmotionalAxis {
    \\  name: string;
    \\  value: number;
    \\  min?: number;
    \\  max?: number;
    \\}
    \\
    \\export interface EmotionalRegister {
    \\  axes: EmotionalAxis[];
    \\  'observed-at'?: string;
    \\}
    \\
    \\export type InteractionKind = 'speak' | 'listen' | 'act' | 'receive';
    \\
    \\export interface Interaction {
    \\  turn: number;
    \\  actor: Fingerprint;
    \\  kind: InteractionKind;
    \\  content?: string;
    \\  timestamp?: string;
    \\  outcome?: string;
    \\}
    \\
    \\export interface InteractionSet {
    \\  'set-id': Base58;
    \\  interactions: Interaction[];
    \\  created?: string;
    \\}
    \\
    \\export interface GuildPolicy {
    \\  public: string[];
    \\  'guild-only': string[];
    \\  'admin-only': string[];
    \\  note?: string;
    \\}
    \\
    \\export interface GuildMembership {
    \\  member: Fingerprint;
    \\  'is-admin'?: boolean;
    \\}
    \\
    \\export interface Guild {
    \\  'guild-name': string;
    \\  'keyspace-root-hash': Bytes32;
    \\  members: GuildMembership[];
    \\  policy?: GuildPolicy;
    \\}
    \\
    \\export interface Relic {
    \\  'sealed-payload-hash': Bytes32;
    \\  'unlock-guild': Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\}
    \\
    \\export interface Transmission {
    \\  'tool-fp': Fingerprint;
    \\  'target-fp': Fingerprint;
    \\  'via-guild': Fingerprint;
    \\  'sender-fp'?: Fingerprint;
    \\  'transmitted-at'?: string;
    \\  'tool-envelope': Base58;   // raw CBOR bytes, base58-wrapped
    \\  signatures?: Signature[];
    \\}
    \\
    \\export interface SecretRef {
    \\  name: string;
    \\  locator: string;
    \\  'issued-by'?: Fingerprint;
    \\  description?: string;
    \\}
    \\
    \\// ===== The top-level DreamBall =====
    \\
    \\export interface DreamBall {
    \\  type: 'jelly.dreamball' | `jelly.dreamball.${DreamBallType}`;
    \\  'format-version': 1 | 2;
    \\  stage: Stage;
    \\  identity: Fingerprint;       // the Ed25519 pubkey in b58
    \\  'genesis-hash': Bytes32;
    \\  revision: number;
    \\  name?: string;
    \\  created?: string;
    \\  updated?: string;
    \\  note?: string;
    \\  look?: Look;
    \\  feel?: Feel;
    \\  act?: Act;
    \\  memory?: Memory;
    \\  'knowledge-graph'?: KnowledgeGraph;
    \\  'emotional-register'?: EmotionalRegister;
    \\  'interaction-set'?: InteractionSet[];
    \\  guild?: Fingerprint[];        // Guild memberships
    \\  contains?: Fingerprint[];
    \\  'derived-from'?: Fingerprint[];
    \\  signatures?: Signature[];
    \\  // Guild-type specific
    \\  'guild-name'?: string;
    \\  'keyspace-root-hash'?: Bytes32;
    \\  member?: Fingerprint[];
    \\  admin?: Fingerprint[];
    \\  policy?: GuildPolicy;
    \\  // Relic-type specific
    \\  'sealed-payload-hash'?: Bytes32;
    \\  'unlock-guild'?: Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\  // Tool-type specific
    \\  skill?: Skill;
    \\  'applicable-to'?: string[];
    \\  // Field-type specific
    \\  'omnispherical-grid'?: OmnisphericalGrid;
    \\  'ambient-palette'?: string[];
    \\  'dream-field-id'?: string;
    \\  // Agent-type specific
    \\  'personality-master-prompt'?: string;
    \\  secret?: SecretRef[];
    \\}
    \\
    \\export interface Vec3 {
    \\  x: number;
    \\  y: number;
    \\  z: number;
    \\}
    \\
    \\export interface CameraRing {
    \\  radius: number;
    \\  tilt: number;
    \\  fov: number;
    \\}
    \\
    \\export interface OmnisphericalGrid {
    \\  'pole-north'?: Vec3;
    \\  'pole-south'?: Vec3;
    \\  'camera-ring'?: CameraRing[];
    \\  'layer-depth'?: number;
    \\  resolution?: number;
    \\  note?: string;
    \\}
    \\
    \\/** Convenience: a DreamBall bundle (the .jelly file) — the envelope
    \\ *  plus optional attachments carried alongside (textures, scripts,
    \\ *  sealed payloads). For most consumers `DreamBall` alone is enough.
    \\ */
    \\export interface JellyBundle {
    \\  envelope: DreamBall;
    \\  attachments: Uint8Array[];
    \\  flags: {
    \\    compressed: boolean;
    \\    encrypted: boolean;
    \\    attachmentsEncrypted: boolean;
    \\  };
    \\  version: number;
    \\}
    \\
    \\export const FORMAT_VERSION = 1 as const;
    \\export const FORMAT_VERSION_V2 = 2 as const;
    \\
    \\export const DREAMBALL_TYPES: readonly DreamBallType[] = [
    \\  'avatar',
    \\  'agent',
    \\  'tool',
    \\  'relic',
    \\  'field',
    \\  'guild',
    \\] as const;
    \\
;

const CBOR_SRC =
    \\// AUTO-GENERATED by tools/schema-gen — do not edit by hand.
    \\// Regenerate with `bun run codegen`.
    \\//
    \\// Minimal dCBOR decoder. Matches the subset emitted by the Zig
    \\// encoder in src/envelope.zig: tags 200 (envelope) / 201 (leaf) /
    \\// 1 (epoch time), canonical map-key ordering, smallest-int form,
    \\// text/bytes/array/map/uint/f64. Floats only appear inside the
    \\// jelly.omnispherical-grid / jelly.memory / jelly.emotional-register
    \\// envelopes — see docs/PROTOCOL.md §12.2.
    \\//
    \\// For v2 MVP we only need decode (incoming .jelly files from the
    \\// jelly-server). Encode path stays on the Zig side.
    \\
    \\export const TAG_EPOCH = 1;
    \\export const TAG_ENVELOPE = 200;
    \\export const TAG_LEAF = 201;
    \\
    \\export class CborReader {
    \\  private cursor = 0;
    \\  constructor(private readonly bytes: Uint8Array) {}
    \\
    \\  atEnd(): boolean {
    \\    return this.cursor >= this.bytes.length;
    \\  }
    \\
    \\  private takeByte(): number {
    \\    if (this.cursor >= this.bytes.length) throw new Error('cbor: truncated');
    \\    return this.bytes[this.cursor++];
    \\  }
    \\
    \\  private readHead(): { major: number; arg: number | bigint } {
    \\    const b = this.takeByte();
    \\    const major = b >> 5;
    \\    const info = b & 0x1f;
    \\    if (info < 24) return { major, arg: info };
    \\    if (info === 24) return { major, arg: this.takeByte() };
    \\    if (info === 25) {
    \\      const hi = this.takeByte();
    \\      const lo = this.takeByte();
    \\      return { major, arg: (hi << 8) | lo };
    \\    }
    \\    if (info === 26) {
    \\      let v = 0;
    \\      for (let i = 0; i < 4; i++) v = (v << 8) | this.takeByte();
    \\      return { major, arg: v >>> 0 };
    \\    }
    \\    if (info === 27) {
    \\      let v = 0n;
    \\      for (let i = 0; i < 8; i++) v = (v << 8n) | BigInt(this.takeByte());
    \\      return { major, arg: v };
    \\    }
    \\    throw new Error(`cbor: unsupported info ${info}`);
    \\  }
    \\
    \\  readAny(): unknown {
    \\    const { major, arg } = this.readHead();
    \\    switch (major) {
    \\      case 0: return typeof arg === 'bigint' ? arg : arg;
    \\      case 1: return typeof arg === 'bigint' ? -(arg + 1n) : -(arg + 1);
    \\      case 2: return this.readByteString(Number(arg));
    \\      case 3: return this.readTextString(Number(arg));
    \\      case 4: {
    \\        const len = Number(arg);
    \\        const out: unknown[] = [];
    \\        for (let i = 0; i < len; i++) out.push(this.readAny());
    \\        return out;
    \\      }
    \\      case 5: {
    \\        const len = Number(arg);
    \\        const out: Record<string, unknown> = {};
    \\        for (let i = 0; i < len; i++) {
    \\          const k = this.readAny();
    \\          const v = this.readAny();
    \\          if (typeof k !== 'string') throw new Error('cbor: map key must be text');
    \\          out[k] = v;
    \\        }
    \\        return out;
    \\      }
    \\      case 6: {
    \\        const inner = this.readAny();
    \\        return { __cborTag: Number(arg), value: inner };
    \\      }
    \\      case 7: {
    \\        if (arg === 20) return false;
    \\        if (arg === 21) return true;
    \\        if (arg === 22) return null;
    \\        if (arg === 23) return undefined;
    \\        if (typeof arg === 'bigint') {
    \\          // float64 (info 27)
    \\          const buf = new ArrayBuffer(8);
    \\          const view = new DataView(buf);
    \\          view.setBigUint64(0, arg);
    \\          return view.getFloat64(0);
    \\        }
    \\        throw new Error(`cbor: unsupported simple ${arg}`);
    \\      }
    \\      default:
    \\        throw new Error(`cbor: unsupported major ${major}`);
    \\    }
    \\  }
    \\
    \\  private readByteString(len: number): Uint8Array {
    \\    if (this.cursor + len > this.bytes.length) throw new Error('cbor: truncated');
    \\    const out = this.bytes.slice(this.cursor, this.cursor + len);
    \\    this.cursor += len;
    \\    return out;
    \\  }
    \\
    \\  private readTextString(len: number): string {
    \\    const slice = this.readByteString(len);
    \\    return new TextDecoder().decode(slice);
    \\  }
    \\}
    \\
    \\/** Decode a .jelly envelope's top-level structure into a
    \\ *  human-readable JS object. Preserves CBOR tags via `__cborTag`
    \\ *  wrappers so callers can introspect envelope/leaf boundaries.
    \\ */
    \\export function decodeEnvelope(bytes: Uint8Array): unknown {
    \\  const reader = new CborReader(bytes);
    \\  return reader.readAny();
    \\}
    \\
    \\/** Convert bytes to the "b58:..." string used in the JSON export. */
    \\export function toBase58Tagged(bytes: Uint8Array): `b58:${string}` {
    \\  return `b58:${base58Encode(bytes)}`;
    \\}
    \\
    \\/** Bitcoin base58 — sufficient for protocol-adjacent short strings. */
    \\export function base58Encode(bytes: Uint8Array): string {
    \\  const alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
    \\  if (bytes.length === 0) return '';
    \\  let leadingZeros = 0;
    \\  while (leadingZeros < bytes.length && bytes[leadingZeros] === 0) leadingZeros++;
    \\  let digits: number[] = [];
    \\  for (const b of bytes) {
    \\    let carry = b;
    \\    for (let i = 0; i < digits.length; i++) {
    \\      carry += digits[i] * 256;
    \\      digits[i] = carry % 58;
    \\      carry = Math.floor(carry / 58);
    \\    }
    \\    while (carry) {
    \\      digits.push(carry % 58);
    \\      carry = Math.floor(carry / 58);
    \\    }
    \\  }
    \\  let out = '1'.repeat(leadingZeros);
    \\  for (let i = digits.length - 1; i >= 0; i--) out += alphabet[digits[i]];
    \\  return out;
    \\}
    \\
    \\export function base58Decode(s: string): Uint8Array {
    \\  const alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
    \\  if (s.length === 0) return new Uint8Array();
    \\  let leadingOnes = 0;
    \\  while (leadingOnes < s.length && s[leadingOnes] === '1') leadingOnes++;
    \\  const bytes: number[] = [];
    \\  for (const ch of s) {
    \\    let carry = alphabet.indexOf(ch);
    \\    if (carry < 0) throw new Error(`base58: invalid char '${ch}'`);
    \\    for (let i = 0; i < bytes.length; i++) {
    \\      carry += bytes[i] * 58;
    \\      bytes[i] = carry & 0xff;
    \\      carry >>= 8;
    \\    }
    \\    while (carry) {
    \\      bytes.push(carry & 0xff);
    \\      carry >>= 8;
    \\    }
    \\  }
    \\  const out = new Uint8Array(leadingOnes + bytes.length);
    \\  for (let i = 0; i < bytes.length; i++) out[leadingOnes + i] = bytes[bytes.length - 1 - i];
    \\  return out;
    \\}
    \\
    \\/** Decode a Base58Tagged value ("b58:...") back to bytes. */
    \\export function fromBase58Tagged(s: string): Uint8Array {
    \\  if (!s.startsWith('b58:')) throw new Error(`expected b58: prefix, got '${s.slice(0, 8)}...'`);
    \\  return base58Decode(s.slice(4));
    \\}
    \\
;

const README_SRC =
    \\# `src/lib/generated/`
    \\
    \\Every file in this directory is **generated** by `tools/schema-gen`.
    \\Do not edit by hand — changes will be overwritten by
    \\`bun run codegen` or `zig build schemagen`.
    \\
    \\## What lives here
    \\
    \\- `types.ts` — TypeScript interfaces mirroring the Zig protocol
    \\  surface (`src/protocol.zig` + `src/protocol_v2.zig`). These drive
    \\  the renderer library and the showcase app's type-safety story.
    \\- `cbor.ts` — minimal dCBOR decoder + base58 helpers for consuming
    \\  `.jelly` bytes when the lib receives them directly (vs. going
    \\  through the `jelly-server` HTTP shim which returns JSON).
    \\
    \\## Why it's generated, not hand-written
    \\
    \\The Zig side is the canonical source of truth for the wire format.
    \\Hand-maintaining a parallel TypeScript schema drifts the moment the
    \\protocol ships a new envelope — see the MTG-style type taxonomy
    \\in `docs/VISION.md §10`, which added six types in a single sprint.
    \\
    \\The generator is a Zig program so it can (in future) introspect
    \\the actual `src/protocol.zig` structs via comptime reflection.
    \\For this first cut the schema is hard-coded inside
    \\`tools/schema-gen/main.zig` — change it there, re-run `bun run
    \\codegen`, commit the updated outputs.
    \\
    \\## Why types.ts uses string literals for `type` discriminants
    \\
    \\The CBOR subject carries `type: "jelly.dreamball.avatar"` (etc.).
    \\Mirroring that as a string literal type in TypeScript means the
    \\compiler can narrow on `ball.type === 'jelly.dreamball.avatar'`
    \\and give you the right assertion surface for that variant. The
    \\short-tag form (`'avatar' | 'agent' | ...`) also appears as
    \\`DreamBallType` for CLI-adjacent UIs.
    \\
    \\## Why floats show up in cbor.ts
    \\
    \\v1's protocol disallows floats. v2 carves out one exception for
    \\spatial data (omnispherical grids, emotional axes) — see
    \\`docs/PROTOCOL.md §12.2`. The CBOR decoder must handle
    \\IEEE-754 float64 values (major type 7, info 27) so that these
    \\envelopes round-trip.
    \\
;

pub fn main() !void {
    var gpa_state: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa_state.deinit();
    const gpa = gpa_state.allocator();

    const io = std.Io.Threaded.global_single_threaded.io();

    // Ensure src/lib/generated/ exists.
    std.Io.Dir.cwd().createDirPath(io, "src/lib/generated") catch |e| switch (e) {
        error.PathAlreadyExists => {},
        else => return e,
    };

    try writeFile(TYPES_OUT, TYPES_SRC);
    try writeFile(CBOR_OUT, CBOR_SRC);
    try writeFile(README_OUT, README_SRC);

    _ = gpa;
    const stdout = std.Io.File.stdout();
    var buf: [256]u8 = undefined;
    var w = stdout.writer(io, &buf);
    try w.interface.print(
        "schema-gen wrote: {s}, {s}, {s}\n",
        .{ TYPES_OUT, CBOR_OUT, README_OUT },
    );
    try w.interface.flush();
}

fn writeFile(path: []const u8, contents: []const u8) !void {
    const io = std.Io.Threaded.global_single_threaded.io();
    var file = try std.Io.Dir.cwd().createFile(io, path, .{ .truncate = true });
    defer file.close(io);
    var buf: [4096]u8 = undefined;
    var w = file.writer(io, &buf);
    try w.interface.writeAll(contents);
    try w.interface.flush();
}
