// dreamball.wasm — ball/1 ABI type declarations.
// Single host import seam: env.getRandomBytes (see docs/VISION.md §14, ADR-1).
// Generated by scripts/build-vendor-wasm.sh — do not edit by hand.

export interface DreamballWasmImports {
  env: {
    /** Host CSPRNG: write `len` random bytes to module memory at `ptr`. */
    getRandomBytes(ptr: number, len: number): void;
  };
}

/** Exports of the instantiated dreamball.wasm module (ball/1). */
export interface BallWasmExports {
  memory: WebAssembly.Memory;
  /** Bump-allocate `size` bytes; returns the pointer (0 on failure). */
  alloc(size: number): number;
  /** Reset the bump allocator between operations. */
  reset(): void;
  /** Parse a .ball CBOR/JSON envelope. Returns packed (resultPtr<<32 | len); 0 on error. */
  parseBall(ptr: number, len: number): bigint;
  /** Verify signatures. 2 = ok+signed, 1 = ok+unsigned, 0 = fail, -1 = parse error. */
  verifyBall(ptr: number, len: number): number;
  mintDreamBall(...args: number[]): bigint;
  growDreamBall(...args: number[]): bigint;
  joinGuildWasm(...args: number[]): bigint;
  signActionEnvelope(...args: number[]): bigint;
  verifyMlDsa(...args: number[]): number;
  hashBlake3(ptr: number, len: number, outPtr: number): void;
  resultErrPtr(): number;
  resultErrLen(): number;
}
