// AUTO-GENERATED by tools/schema-gen — spike fixture (Story 1.1).
// Scope: CBOR codec stubs for Envelope (DreamBall), SealedBody (Relic),
// SignatureTierWrapper (Signature). The CBOR algorithm itself stays
// canonical in Zig (D-018); this file emits ONLY the wire-tag constants
// + base58 helpers consumed by the typed decoders. Do not edit by hand.

export const TAG_EPOCH = 1;
export const TAG_ENVELOPE = 200;
export const TAG_LEAF = 201;
