// AUTO-GENERATED by tools/schema-gen — spike fixture (Story 1.1).
// Scope: Valibot schemas for Envelope (DreamBall), SealedBody (Relic),
// SignatureTierWrapper (Signature + Stage). Source of truth:
// tools/schema-gen/main.zig SCHEMAS_SRC. Do not edit by hand.

import * as v from 'valibot';

export const Base58Schema = v.pipe(
  v.string(),
  v.regex(/^b58:[1-9A-HJ-NP-Za-km-z]*$/, 'expected "b58:..." prefix')
);

export const Rfc3339Schema = v.pipe(
  v.string(),
  v.regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/, 'expected RFC3339 UTC')
);

export const SignatureAlgSchema = v.picklist(['ed25519', 'ml-dsa-87']);

export const SignatureSchema = v.object({
  alg: SignatureAlgSchema,
  value: Base58Schema
});

export const StageSchema = v.picklist(['seed', 'dreamball', 'dragonball']);

export const RelicSchema = v.object({
  'sealed-payload-hash': Base58Schema,
  'unlock-guild': Base58Schema,
  'reveal-hint': v.optional(v.string()),
  'sealed-until': v.optional(Rfc3339Schema)
});

const commonCore = {
  stage: StageSchema,
  identity: Base58Schema,
  'genesis-hash': Base58Schema,
  revision: v.number(),
  'format-version': v.union([v.literal(1), v.literal(2)]),
  name: v.optional(v.string()),
  created: v.optional(Rfc3339Schema),
  updated: v.optional(Rfc3339Schema),
  note: v.optional(v.string()),
  signatures: v.optional(v.array(SignatureSchema))
};

export const DreamBallRelicSchema = v.object({
  ...commonCore,
  type: v.literal('ball.dreamball.relic'),
  'sealed-payload-hash': Base58Schema,
  'unlock-guild': Base58Schema,
  'reveal-hint': v.optional(v.string()),
  'sealed-until': v.optional(Rfc3339Schema)
});
