import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';

// The WASM must already be built (`zig build wasm`) — this test consumes
// the .wasm bytes directly via fs rather than the Vite `?url` import, so
// the same test runs in Node without a browser.

async function buildInstance() {
	const wasmPath = resolve(__dirname, 'jelly.wasm');
	const bytes = readFileSync(wasmPath);
	const mod = await WebAssembly.compile(bytes);
	const inst = await WebAssembly.instantiate(mod, {});
	return inst.exports as unknown as {
		memory: WebAssembly.Memory;
		alloc: (n: number) => number;
		reset: () => void;
		parseJelly: (ptr: number, len: number) => bigint;
		resultErrPtr: () => number;
		resultErrLen: () => number;
	};
}

describe('jelly-wasm loader', () => {
	let wasm: Awaited<ReturnType<typeof buildInstance>>;

	beforeAll(async () => {
		wasm = await buildInstance();
	});

	it('parses a bare CBOR tag-200 envelope (generated by a minimal subject)', async () => {
		// Minimal bare envelope: tag 200 → tag 201 → subject map with the
		// six required subject fields. We use a known-good byte sequence
		// produced by encoding an all-zeros seed via the Zig CLI — the
		// same fixture used by the golden-bytes lock in src/golden.zig.
		//
		// Structure:
		//   0xD8 0xC8               tag 200 (envelope)
		//   0xD8 0xC9               tag 201 (leaf)
		//   0xA6                    map(6)
		//     "type"          "jelly.dreamball"
		//     "stage"         "seed"
		//     "identity"      bytes(32)  all zeros
		//     "revision"      0
		//     "genesis-hash"  bytes(32)  all zeros
		//     "format-version" 1
		//
		// Keys emitted in dCBOR canonical order (len ascending, lex tiebreak).
		const bytes = new Uint8Array([
			0xd8, 0xc8, 0xd8, 0xc9, 0xa6,
			// "type"
			0x64, 0x74, 0x79, 0x70, 0x65,
			0x6f, 0x6a, 0x65, 0x6c, 0x6c, 0x79, 0x2e, 0x64, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x61, 0x6c, 0x6c,
			// "stage"
			0x65, 0x73, 0x74, 0x61, 0x67, 0x65,
			0x64, 0x73, 0x65, 0x65, 0x64,
			// "identity" + 32 bytes
			0x68, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
			0x58, 0x20,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			// "revision"
			0x68, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
			0x00,
			// "genesis-hash" + 32 bytes
			0x6c, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x2d, 0x68, 0x61, 0x73, 0x68,
			0x58, 0x20,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			// "format-version"
			0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
			0x01
		]);

		wasm.reset();
		const ptr = wasm.alloc(bytes.length);
		expect(ptr).toBeGreaterThan(0);
		new Uint8Array(wasm.memory.buffer, ptr, bytes.length).set(bytes);

		const packed = wasm.parseJelly(ptr, bytes.length);
		expect(packed).not.toBe(0n);

		const resultPtr = Number(packed >> 32n);
		const resultLen = Number(packed & 0xffffffffn);
		const jsonText = new TextDecoder().decode(
			new Uint8Array(wasm.memory.buffer, resultPtr, resultLen)
		);
		const parsed = JSON.parse(jsonText);

		expect(parsed.type).toBe('jelly.dreamball');
		expect(parsed.stage).toBe('seed');
		expect(parsed['format-version']).toBe(1);
		expect(parsed.revision).toBe(0);
		expect(parsed.identity).toMatch(/^b58:/);
		expect(parsed['genesis-hash']).toMatch(/^b58:/);
	});

	it('reports a clean error on garbage input', async () => {
		const bytes = new Uint8Array([0xff, 0xff, 0xff, 0xff]);
		wasm.reset();
		const ptr = wasm.alloc(bytes.length);
		new Uint8Array(wasm.memory.buffer, ptr, bytes.length).set(bytes);
		const packed = wasm.parseJelly(ptr, bytes.length);
		expect(packed).toBe(0n);
		const ep = wasm.resultErrPtr();
		const el = wasm.resultErrLen();
		const msg = new TextDecoder().decode(new Uint8Array(wasm.memory.buffer, ep, el));
		expect(msg.toLowerCase()).toMatch(/unknown|format/);
	});

	it('echoes a canonical JSON input', async () => {
		const json = '{"type":"jelly.dreamball","stage":"seed","revision":0}';
		const bytes = new TextEncoder().encode(json);
		wasm.reset();
		const ptr = wasm.alloc(bytes.length);
		new Uint8Array(wasm.memory.buffer, ptr, bytes.length).set(bytes);
		const packed = wasm.parseJelly(ptr, bytes.length);
		expect(packed).not.toBe(0n);
		const resultPtr = Number(packed >> 32n);
		const resultLen = Number(packed & 0xffffffffn);
		const jsonText = new TextDecoder().decode(
			new Uint8Array(wasm.memory.buffer, resultPtr, resultLen)
		);
		expect(jsonText).toContain('"type":"jelly.dreamball"');
	});
});
