import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, statSync } from 'fs';
import { resolve } from 'path';
import { execSync } from 'child_process';
import { mkdtempSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { gzipSync } from 'zlib';

// End-to-end verify test. Mints a real DreamBall via the Zig CLI,
// loads the bytes, calls the WASM verifier. Confirms:
//   - pristine envelope verifies
//   - tampered envelope rejects
// This is the "browser acts as independent verifier" proof.

const WASM_PATH = resolve(__dirname, 'jelly.wasm');
const JELLY_CLI = resolve(__dirname, '..', '..', '..', 'zig-out', 'bin', 'jelly');

async function loadWasm() {
	const bytes = readFileSync(WASM_PATH);
	const mod = await WebAssembly.compile(bytes);
	let inst!: WebAssembly.Instance;
	const env = {
		getRandomBytes(ptr: number, len: number) {
			const mem = (inst.exports.memory as WebAssembly.Memory).buffer;
			crypto.getRandomValues(new Uint8Array(mem, ptr, len));
		}
	};
	inst = await WebAssembly.instantiate(mod, { env });
	return inst.exports as unknown as {
		memory: WebAssembly.Memory;
		alloc: (n: number) => number;
		reset: () => void;
		verifyJelly: (ptr: number, len: number) => number;
		resultErrPtr: () => number;
		resultErrLen: () => number;
	};
}

describe('WASM verifyJelly', () => {
	let wasm: Awaited<ReturnType<typeof loadWasm>>;
	let pristineBytes: Uint8Array;
	let tamperedBytes: Uint8Array;

	beforeAll(async () => {
		wasm = await loadWasm();

		const workdir = mkdtempSync(join(tmpdir(), 'jelly-verify-'));
		const jellyPath = join(workdir, 'test.jelly');

		// Mint a real DreamBall via the Zig CLI.
		execSync(`${JELLY_CLI} mint --out ${jellyPath} --type avatar --name test`, { stdio: 'pipe' });
		pristineBytes = new Uint8Array(readFileSync(jellyPath));

		// Tamper: flip a byte inside the signed region.
		const copy = new Uint8Array(pristineBytes);
		copy[60] ^= 0x01;
		tamperedBytes = copy;
	});

	function verify(bytes: Uint8Array): { code: number; reason: string } {
		wasm.reset();
		const ptr = wasm.alloc(bytes.length);
		new Uint8Array(wasm.memory.buffer, ptr, bytes.length).set(bytes);
		const code = wasm.verifyJelly(ptr, bytes.length);
		const ep = wasm.resultErrPtr();
		const el = wasm.resultErrLen();
		const reason = new TextDecoder().decode(new Uint8Array(wasm.memory.buffer, ep, el));
		return { code, reason };
	}

	it('verifies a pristine mint', () => {
		const { code } = verify(pristineBytes);
		expect(code).toBe(2);
	});

	it('rejects a tampered byte', () => {
		const { code, reason } = verify(tamperedBytes);
		// Either the signature fails (code 0) or the envelope no longer
		// parses cleanly (code -1); both are acceptable rejections.
		expect([-1, 0]).toContain(code);
		expect(reason.length).toBeGreaterThan(0);
	});

	it('rejects garbage input', () => {
		const garbage = new Uint8Array([0xff, 0xff, 0xff, 0xff]);
		const { code } = verify(garbage);
		expect(code).toBe(-1);
	});
});

// ---------------------------------------------------------------------------
// ML-DSA-87 WASM verify (primitive) — D-010 / AC1–AC3
//
// Tests the standalone verifyMlDsa(sig, msg, pk) export directly against
// a pinned known-answer-test vector in fixtures/ml_dsa_87_golden.json.
// The fixture is generated by `zig build export-mldsa-fixture` using a
// seeded PRNG so it is deterministic and safe to commit.
//
// Playwright+Chromium coverage is deferred — see Dev Agent Record in
// docs/sprints/001-memory-palace-mvp/stories/epic-1.md.
// ---------------------------------------------------------------------------

const FIXTURE_PATH = resolve(__dirname, '..', '..', '..', 'fixtures', 'ml_dsa_87_golden.json');

interface MlDsaFixture {
	pk: string;
	msg: string;
	sig: string;
}

function hexToBytes(hex: string): Uint8Array {
	const out = new Uint8Array(hex.length / 2);
	for (let i = 0; i < out.length; i++) {
		out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
	}
	return out;
}

async function loadWasmWithMlDsa() {
	const bytes = readFileSync(WASM_PATH);
	const mod = await WebAssembly.compile(bytes);
	let inst!: WebAssembly.Instance;
	const env = {
		getRandomBytes(ptr: number, len: number) {
			const mem = (inst.exports.memory as WebAssembly.Memory).buffer;
			crypto.getRandomValues(new Uint8Array(mem, ptr, len));
		}
	};
	inst = await WebAssembly.instantiate(mod, { env });
	return inst.exports as unknown as {
		memory: WebAssembly.Memory;
		alloc: (n: number) => number;
		reset: () => void;
		verifyMlDsa: (
			sigPtr: number, sigLen: number,
			msgPtr: number, msgLen: number,
			pkPtr: number, pkLen: number
		) => number;
		resultErrPtr: () => number;
		resultErrLen: () => number;
	};
}

describe('ML-DSA-87 WASM verify (primitive)', () => {
	let wasm: Awaited<ReturnType<typeof loadWasmWithMlDsa>>;
	let fx: MlDsaFixture;
	let pk: Uint8Array;
	let msg: Uint8Array;
	let sig: Uint8Array;

	beforeAll(async () => {
		wasm = await loadWasmWithMlDsa();
		fx = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as MlDsaFixture;
		pk = hexToBytes(fx.pk);
		msg = hexToBytes(fx.msg);
		sig = hexToBytes(fx.sig);
	});

	function callVerifyMlDsa(
		sigBytes: Uint8Array,
		msgBytes: Uint8Array,
		pkBytes: Uint8Array
	): { ok: boolean; err: string } {
		wasm.reset();
		const sigPtr = wasm.alloc(sigBytes.length);
		const msgPtr = wasm.alloc(msgBytes.length);
		const pkPtr  = wasm.alloc(pkBytes.length);
		new Uint8Array(wasm.memory.buffer, sigPtr, sigBytes.length).set(sigBytes);
		new Uint8Array(wasm.memory.buffer, msgPtr, msgBytes.length).set(msgBytes);
		new Uint8Array(wasm.memory.buffer, pkPtr,  pkBytes.length).set(pkBytes);
		const rc = wasm.verifyMlDsa(
			sigPtr, sigBytes.length,
			msgPtr, msgBytes.length,
			pkPtr,  pkBytes.length
		);
		const ep = wasm.resultErrPtr();
		const el = wasm.resultErrLen();
		const err = new TextDecoder().decode(new Uint8Array(wasm.memory.buffer, ep, el));
		return { ok: rc === 1, err };
	}

	it('AC1 happy: golden fixture verifies', () => {
		const { ok } = callVerifyMlDsa(sig, msg, pk);
		expect(ok).toBe(true);
	});

	it('AC2 sig tamper: bit-flipped sig byte 0 returns false, no throw', () => {
		const tampered = new Uint8Array(sig);
		tampered[0] ^= 1;
		const { ok } = callVerifyMlDsa(tampered, msg, pk);
		expect(ok).toBe(false);
	});

	it('AC3 msg tamper: bit-flipped msg byte 0 returns false, no throw', () => {
		const tamperedMsg = new Uint8Array(msg);
		tamperedMsg[0] ^= 1;
		const { ok } = callVerifyMlDsa(sig, tamperedMsg, pk);
		expect(ok).toBe(false);
	});
});

// ---------------------------------------------------------------------------
// AC4 — WASM binary size budget (TC5: ≤200 KB raw / ≤64 KB gzipped)
// Colocated here per Story 1.1 spec so the budget assertion travels with
// the verify coverage. CI also enforces this at .github/workflows/ci.yml.
// ---------------------------------------------------------------------------

describe('WASM binary budget (TC5)', () => {
	it('raw size ≤ 204800 bytes and gzip size ≤ 65536 bytes', () => {
		const raw = statSync(WASM_PATH).size;
		const gzip = gzipSync(readFileSync(WASM_PATH)).length;
		expect(raw).toBeLessThanOrEqual(204800);
		expect(gzip).toBeLessThanOrEqual(65536);
	});
});
