/**
 * perf-fixtures.ts — Deterministic 500-inscription corpus generator (S6.3 AC3).
 *
 * Generates a seeded, reproducible corpus of N inscriptions, each with a
 * pre-computed 256d embedding vector. The embeddings are pure math (seeded
 * LCG) — no Qwen3 cold-start during measurement.
 *
 * Perf test discipline (AC3, R5 mitigation):
 *   - Measure ONLY the kNN query round-trip (query-embed + vector-index lookup).
 *   - Corpus SETUP (500 CREATE + upsertEmbedding) is NOT included in the budget.
 *   - p50 end-to-end <200ms hard gate.
 *   - p95 <400ms soft ceiling (breach → warn + ADR addendum, not fail).
 *
 * Usage:
 *   import { generatePerfCorpus, type PerfInscription } from './perf-fixtures.js';
 *   const corpus = generatePerfCorpus(500, 256, 42);
 *   // corpus[i].fp   — Blake3-style hex fp (deterministic from seed)
 *   // corpus[i].vec  — Float32Array(256), L2-normalised
 *   // corpus[i].roomFp — which room this inscription lives in (round-robin 5 rooms)
 *
 * Generator algorithm:
 *   Linear-congruential generator (LCG) seeded from `seed`. For each inscription:
 *   - fp: 'perf-' + i.toString().padStart(5, '0') (stable, unique, no hashing)
 *   - vec: 256 LCG floats mapped to [-1,1], then L2-normalised
 *   - roomFp: 'room-' + (i % NUM_ROOMS).toString().padStart(3, '0')
 *
 * L2 normalisation ensures cosine distance is well-defined and bounded [0,2].
 *
 * NFRs: NFR10 (perf budget), NFR13 (no network calls in fixture generation).
 */

/** Number of rooms in the perf corpus (inscriptions round-robin). */
export const PERF_ROOM_COUNT = 5;

/** A single pre-computed fixture inscription. */
export interface PerfInscription {
  /** Deterministic inscription fingerprint (e.g. 'perf-00042'). */
  fp: string;
  /** Deterministic room fingerprint (round-robin across PERF_ROOM_COUNT rooms). */
  roomFp: string;
  /** Pre-computed 256d L2-normalised embedding vector. */
  vec: Float32Array;
  /** Deterministic source blake3 hash (hex, 64 chars). Used for upsertEmbedding. */
  sourceBlake3: string;
}

// ── LCG parameters (Numerical Recipes) ───────────────────────────────────────

const LCG_A = 1664525;
const LCG_C = 1013904223;
const LCG_M = 2 ** 32;

function lcgNext(state: number): number {
  return (LCG_A * state + LCG_C) % LCG_M;
}

function lcgFloat(state: number): number {
  // Map [0, 2^32) → [-1, 1)
  return (state / LCG_M) * 2 - 1;
}

// ── Corpus generator ─────────────────────────────────────────────────────────

/**
 * Generate a deterministic 256d inscription corpus.
 *
 * @param n    Number of inscriptions (default 500 per AC3).
 * @param dim  Embedding dimension (default 256 per D-002 / MRL).
 * @param seed Initial LCG seed (default 42 for reproducibility).
 */
export function generatePerfCorpus(n = 500, dim = 256, seed = 42): PerfInscription[] {
  const corpus: PerfInscription[] = [];
  let state = seed;

  for (let i = 0; i < n; i++) {
    // Generate dim raw floats
    const raw = new Float32Array(dim);
    for (let d = 0; d < dim; d++) {
      state = lcgNext(state);
      raw[d] = lcgFloat(state);
    }

    // L2-normalise
    let norm = 0;
    for (let d = 0; d < dim; d++) norm += raw[d] * raw[d];
    norm = Math.sqrt(norm);
    if (norm > 0) {
      for (let d = 0; d < dim; d++) raw[d] /= norm;
    }

    // Deterministic fp: valid 64-char hex string derived from index
    // Format: index encoded as 16-char hex, repeated 4 times.
    const fp = i.toString(16).padStart(16, '0').repeat(4);

    // Round-robin room assignment — valid 64-char hex derived from room index
    const roomIdx = i % PERF_ROOM_COUNT;
    const roomFp = (0xf000 + roomIdx).toString(16).padStart(16, '0').repeat(4);

    // Deterministic source blake3: valid 64-char hex from seed + i
    const sourceBlake3 = (seed * 1000000 + i + 1).toString(16).padStart(16, '0').repeat(4);

    corpus.push({ fp, roomFp, vec: raw, sourceBlake3 });
  }

  return corpus;
}

/**
 * Generate a deterministic query vector for perf testing.
 *
 * Uses a different seed than the corpus to ensure the query is not
 * identical to any corpus vector.
 *
 * @param dim  Embedding dimension (default 256).
 * @param seed LCG seed (default 99 — different from corpus seed 42).
 */
export function generatePerfQueryVector(dim = 256, seed = 99): Float32Array {
  const raw = new Float32Array(dim);
  let state = seed;
  for (let d = 0; d < dim; d++) {
    state = lcgNext(state);
    raw[d] = lcgFloat(state);
  }

  let norm = 0;
  for (let d = 0; d < dim; d++) norm += raw[d] * raw[d];
  norm = Math.sqrt(norm);
  if (norm > 0) {
    for (let d = 0; d < dim; d++) raw[d] /= norm;
  }

  return raw;
}

/**
 * Return the room fps used by a corpus generated with PERF_ROOM_COUNT rooms.
 * Stable: always valid 64-char hex fps matching the roomFp generated by generatePerfCorpus.
 */
export function perfRoomFps(roomCount = PERF_ROOM_COUNT): string[] {
  return Array.from({ length: roomCount }, (_, i) =>
    (0xf000 + i).toString(16).padStart(16, '0').repeat(4)
  );
}
