#!/usr/bin/env bash
# Emit the depend-able dreamball.wasm vendor bundle for external consumers
# (e.g. the web/ client repo). Produces a self-contained directory under
# release/dreamball-wasm/ with the binary, a type declaration, a SHA-256
# checksum, and a provenance note. Re-runnable + checked in CI (the
# `vendor-wasm-checksum` job rebuilds and asserts the committed checksum).
#
# Decision: this repo EMITS the artifact; it does not vendor it. See
# docs/decisions and CLAUDE.md. ball/1 epoch, package 0.1.0.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"
OUT="release/dreamball-wasm"
WASM_SRC="src/lib/wasm/dreamball.wasm"

echo "==> zig build wasm"
zig build wasm

mkdir -p "$OUT"
cp "$WASM_SRC" "$OUT/dreamball.wasm"

# Type declaration for the WASM module's host seam + exports (ball/1 ABI).
cat > "$OUT/dreamball.d.ts" <<'DTS'
// dreamball.wasm — ball/1 ABI type declarations.
// Single host import seam: env.getRandomBytes (see docs/VISION.md §14, ADR-1).
// Generated by scripts/build-vendor-wasm.sh — do not edit by hand.

export interface DreamballWasmImports {
  env: {
    /** Host CSPRNG: write `len` random bytes to module memory at `ptr`. */
    getRandomBytes(ptr: number, len: number): void;
  };
}

/** Exports of the instantiated dreamball.wasm module (ball/1). */
export interface BallWasmExports {
  memory: WebAssembly.Memory;
  /** Bump-allocate `size` bytes; returns the pointer (0 on failure). */
  alloc(size: number): number;
  /** Reset the bump allocator between operations. */
  reset(): void;
  /** Parse a .ball CBOR/JSON envelope. Returns packed (resultPtr<<32 | len); 0 on error. */
  parseBall(ptr: number, len: number): bigint;
  /** Verify signatures. 2 = ok+signed, 1 = ok+unsigned, 0 = fail, -1 = parse error. */
  verifyBall(ptr: number, len: number): number;
  mintDreamBall(...args: number[]): bigint;
  growDreamBall(...args: number[]): bigint;
  joinGuildWasm(...args: number[]): bigint;
  signActionEnvelope(...args: number[]): bigint;
  verifyMlDsa(...args: number[]): number;
  hashBlake3(ptr: number, len: number, outPtr: number): void;
  resultErrPtr(): number;
  resultErrLen(): number;
}
DTS

# Checksum + provenance.
RAW=$(wc -c < "$OUT/dreamball.wasm" | tr -d ' ')
GZ=$(gzip -9c "$OUT/dreamball.wasm" | wc -c | tr -d ' ')
if command -v sha256sum >/dev/null 2>&1; then
  SHA=$(sha256sum "$OUT/dreamball.wasm" | awk '{print $1}')
else
  SHA=$(shasum -a 256 "$OUT/dreamball.wasm" | awk '{print $1}')
fi
COMMIT=$(git rev-parse HEAD)

printf '%s  dreamball.wasm\n' "$SHA" > "$OUT/dreamball.wasm.sha256"

cat > "$OUT/PROVENANCE.md" <<PROV
# dreamball.wasm — provenance

- **Protocol epoch:** ball/1 (package 0.1.0)
- **Source commit:** \`$COMMIT\`
- **Build:** \`zig build wasm\` (ML-DSA-87 verify linked; \`-Dpq-wasm=true\` default)
- **SHA-256:** \`$SHA\`
- **Size:** ${RAW} bytes raw, ${GZ} bytes gzipped (budget: ≤ 300 KB raw / ≤ 150 KB gzipped; dev-velocity bump 2026-06-28, tightening tracked in Dreamball-8bk)

Vendor this directory into the consumer (e.g. the web/ client repo). The
binary's only host requirement is one import: \`env.getRandomBytes(ptr, len)\`
backed by a CSPRNG. Types in \`dreamball.d.ts\`. Verify integrity with
\`shasum -a 256 -c dreamball.wasm.sha256\`.

Regenerate with \`scripts/build-vendor-wasm.sh\`.
PROV

echo "==> wrote $OUT/ (raw=${RAW}B gz=${GZ}B sha=${SHA:0:16}…)"
