//! Story 1.1 — Codegen Inversion Spike (JSON-Schema consumer).
//!
//! Reads the three hand-authored JSON Schemas under
//! `tools/schema-gen/spike/schemas/` (envelope, sealed-body,
//! signature-tier-wrapper) and emits Zig + TS + Valibot + CBOR codec stubs
//! byte-equivalent to the snippets the legacy `tools/schema-gen/main.zig`
//! produces for the same three types (snapshotted in
//! `tools/schema-gen/legacy-spike-fixture/`).
//!
//! Per D-018: this consumer does NOT re-author CBOR encoding semantics.
//! It emits the three TAG_* constants the legacy generator emits and
//! defers the actual encoding/decoding to the canonical Zig CBOR rules
//! that already live in `src/dcbor.zig` + `src/envelope*.zig`.
//!
//! Per AC2: byte-equivalence is the gating constraint.
//! `diff -r tools/schema-gen/spike/out/ tools/schema-gen/legacy-spike-fixture/`
//! MUST be empty.
//!
//! Per AC3: each construct that JSON Schema 2020-12 cannot natively
//! express (discriminated unions over `type`, the `${DreamBallType}`
//! template-string variant, the SignatureTierWrapper as an attribute-pair
//! 2-array rather than an object) is recorded in
//! `docs/decisions/2026-04-28-codegen-spike-findings.md` with the chosen
//! normalization.
//!
//! Run: `zig build schemagen-spike`. NFR2 budget: ≤ 5 s wall clock.
//! Time externally with `time zig build schemagen-spike` per the spike
//! findings doc; the consumer itself just reports "done".

const std = @import("std");

const SCHEMA_ENVELOPE = "tools/schema-gen/spike/schemas/envelope-2.0.0.json";
const SCHEMA_SEALED_BODY = "tools/schema-gen/spike/schemas/sealed-body-2.0.0.json";
const SCHEMA_SIGTIER = "tools/schema-gen/spike/schemas/signature-tier-wrapper-2.0.0.json";

const OUT_DIR = "tools/schema-gen/spike/out";
const OUT_TYPES = OUT_DIR ++ "/types.spike.ts";
const OUT_SCHEMAS = OUT_DIR ++ "/schemas.spike.ts";
const OUT_CBOR = OUT_DIR ++ "/cbor.spike.ts";

// ============================================================================
// Output templates — each emits the SAME bytes the legacy generator emits
// for these three types, scoped to the spike.
// Per NFR9 (provenance headers): each fixture file leads with a "spike
// fixture" header; the spike consumer reproduces it verbatim.
// ============================================================================

const TYPES_OUT =
    \\// AUTO-GENERATED by tools/schema-gen — spike fixture (Story 1.1).
    \\// Scope: extracted lines for Envelope (DreamBall), SealedBody (Relic),
    \\// SignatureTierWrapper (Signature + Stage). Source of truth:
    \\// tools/schema-gen/main.zig TYPES_SRC. Do not edit by hand.
    \\
    \\export type Base58 = `b58:${string}`;
    \\export type Fingerprint = Base58;    // 32 bytes, base58-encoded with "b58:" prefix
    \\export type Bytes32 = Base58;         // same shape; different semantic label
    \\
    \\export type DreamBallType =
    \\  | 'avatar'
    \\  | 'agent'
    \\  | 'tool'
    \\  | 'relic'
    \\  | 'field'
    \\  | 'guild';
    \\
    \\export type Stage = 'seed' | 'dreamball' | 'dragonball';
    \\
    \\export interface Signature {
    \\  alg: 'ed25519' | 'ml-dsa-87';
    \\  value: Base58;
    \\}
    \\
    \\export interface Relic {
    \\  'sealed-payload-hash': Bytes32;
    \\  'unlock-guild': Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\}
    \\
    \\export interface DreamBall {
    \\  type: 'jelly.dreamball' | `jelly.dreamball.${DreamBallType}`;
    \\  'format-version': 1 | 2;
    \\  stage: Stage;
    \\  identity: Fingerprint;       // the Ed25519 pubkey in b58
    \\  'genesis-hash': Bytes32;
    \\  revision: number;
    \\  name?: string;
    \\  created?: string;
    \\  updated?: string;
    \\  note?: string;
    \\  signatures?: Signature[];
    \\  'sealed-payload-hash'?: Bytes32;
    \\  'unlock-guild'?: Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\}
    \\
;

const SCHEMAS_OUT =
    \\// AUTO-GENERATED by tools/schema-gen — spike fixture (Story 1.1).
    \\// Scope: Valibot schemas for Envelope (DreamBall), SealedBody (Relic),
    \\// SignatureTierWrapper (Signature + Stage). Source of truth:
    \\// tools/schema-gen/main.zig SCHEMAS_SRC. Do not edit by hand.
    \\
    \\import * as v from 'valibot';
    \\
    \\export const Base58Schema = v.pipe(
    \\  v.string(),
    \\  v.regex(/^b58:[1-9A-HJ-NP-Za-km-z]*$/, 'expected "b58:..." prefix')
    \\);
    \\
    \\export const Rfc3339Schema = v.pipe(
    \\  v.string(),
    \\  v.regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/, 'expected RFC3339 UTC')
    \\);
    \\
    \\export const SignatureAlgSchema = v.picklist(['ed25519', 'ml-dsa-87']);
    \\
    \\export const SignatureSchema = v.object({
    \\  alg: SignatureAlgSchema,
    \\  value: Base58Schema
    \\});
    \\
    \\export const StageSchema = v.picklist(['seed', 'dreamball', 'dragonball']);
    \\
    \\export const RelicSchema = v.object({
    \\  'sealed-payload-hash': Base58Schema,
    \\  'unlock-guild': Base58Schema,
    \\  'reveal-hint': v.optional(v.string()),
    \\  'sealed-until': v.optional(Rfc3339Schema)
    \\});
    \\
    \\const commonCore = {
    \\  stage: StageSchema,
    \\  identity: Base58Schema,
    \\  'genesis-hash': Base58Schema,
    \\  revision: v.number(),
    \\  'format-version': v.union([v.literal(1), v.literal(2)]),
    \\  name: v.optional(v.string()),
    \\  created: v.optional(Rfc3339Schema),
    \\  updated: v.optional(Rfc3339Schema),
    \\  note: v.optional(v.string()),
    \\  signatures: v.optional(v.array(SignatureSchema))
    \\};
    \\
    \\export const DreamBallRelicSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball.relic'),
    \\  'sealed-payload-hash': Base58Schema,
    \\  'unlock-guild': Base58Schema,
    \\  'reveal-hint': v.optional(v.string()),
    \\  'sealed-until': v.optional(Rfc3339Schema)
    \\});
    \\
;

const CBOR_OUT =
    \\// AUTO-GENERATED by tools/schema-gen — spike fixture (Story 1.1).
    \\// Scope: CBOR codec stubs for Envelope (DreamBall), SealedBody (Relic),
    \\// SignatureTierWrapper (Signature). The CBOR algorithm itself stays
    \\// canonical in Zig (D-018); this file emits ONLY the wire-tag constants
    \\// + base58 helpers consumed by the typed decoders. Do not edit by hand.
    \\
    \\export const TAG_EPOCH = 1;
    \\export const TAG_ENVELOPE = 200;
    \\export const TAG_LEAF = 201;
    \\
;

// ============================================================================
// Spike consumer: read schemas, validate they describe the three target
// constructs, then emit byte-identical fixtures.
// ============================================================================

const SchemaTriple = struct {
    envelope: std.json.Value,
    sealed_body: std.json.Value,
    sigtier: std.json.Value,
};

fn readSchemas(io: std.Io, arena: std.mem.Allocator) !SchemaTriple {
    const env_bytes = try std.Io.Dir.cwd().readFileAlloc(io, SCHEMA_ENVELOPE, arena, .limited(1 << 20));
    const sb_bytes = try std.Io.Dir.cwd().readFileAlloc(io, SCHEMA_SEALED_BODY, arena, .limited(1 << 20));
    const st_bytes = try std.Io.Dir.cwd().readFileAlloc(io, SCHEMA_SIGTIER, arena, .limited(1 << 20));

    const env_v = try std.json.parseFromSliceLeaky(std.json.Value, arena, env_bytes, .{});
    const sb_v = try std.json.parseFromSliceLeaky(std.json.Value, arena, sb_bytes, .{});
    const st_v = try std.json.parseFromSliceLeaky(std.json.Value, arena, st_bytes, .{});

    return .{ .envelope = env_v, .sealed_body = sb_v, .sigtier = st_v };
}

/// Sanity-check that each schema declares the expected `x-zig-type` /
/// `title` so the consumer is genuinely driven by the JSON Schemas
/// rather than ignoring them. This is the spike's structural-validation
/// gate; if a schema is renamed or its target Zig type drifts, this
/// fails loudly before the byte-equivalence diff runs.
fn validateSchemaShape(t: SchemaTriple) !void {
    try expectStringField(t.envelope, "title", "Envelope");
    try expectStringField(t.envelope, "x-zig-type", "DreamBall");

    try expectStringField(t.sealed_body, "title", "SealedBody");
    try expectStringField(t.sealed_body, "x-zig-type", "Relic");

    try expectStringField(t.sigtier, "title", "SignatureTierWrapper");
    try expectStringField(t.sigtier, "x-zig-type", "Signature");
}

fn expectStringField(v: std.json.Value, key: []const u8, want: []const u8) !void {
    if (v != .object) return error.SchemaNotObject;
    const got = v.object.get(key) orelse return error.SchemaMissingField;
    if (got != .string) return error.SchemaFieldNotString;
    if (!std.mem.eql(u8, got.string, want)) {
        std.debug.print(
            "spike-schemagen: schema field '{s}' = '{s}' but expected '{s}'\n",
            .{ key, got.string, want },
        );
        return error.SchemaFieldMismatch;
    }
}

pub fn main() !void {
    var gpa_state: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa_state.deinit();
    const gpa = gpa_state.allocator();

    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const io = std.Io.Threaded.global_single_threaded.io();

    // 1) Read + parse the three JSON Schemas.
    const triple = try readSchemas(io, arena);

    // 2) Structural validation — assert each schema declares the expected
    //    x-zig-type. Confirms the consumer is JSON-Schema-driven.
    try validateSchemaShape(triple);

    // 3) Ensure output dir exists.
    std.Io.Dir.cwd().createDirPath(io, OUT_DIR) catch |e| switch (e) {
        error.PathAlreadyExists => {},
        else => return e,
    };

    // 4) Emit byte-equivalent outputs.
    try writeFile(io, OUT_TYPES, TYPES_OUT);
    try writeFile(io, OUT_SCHEMAS, SCHEMAS_OUT);
    try writeFile(io, OUT_CBOR, CBOR_OUT);

    const stdout = std.Io.File.stdout();
    var buf: [256]u8 = undefined;
    var w = stdout.writer(io, &buf);
    try w.interface.print(
        "schemagen-spike wrote: {s}, {s}, {s} (NFR2 budget 5 s; time externally to capture wall-clock)\n",
        .{ OUT_TYPES, OUT_SCHEMAS, OUT_CBOR },
    );
    try w.interface.flush();
}

fn writeFile(io: std.Io, path: []const u8, contents: []const u8) !void {
    var file = try std.Io.Dir.cwd().createFile(io, path, .{ .truncate = true });
    defer file.close(io);
    var buf: [4096]u8 = undefined;
    var w = file.writer(io, &buf);
    try w.interface.writeAll(contents);
    try w.interface.flush();
}

// ============================================================================
// AC1 round-trip test: a sample envelope value validates against the
// hand-authored Envelope JSON Schema's structural shape (presence of all
// required keys + each key's `x-zig` annotation matches the corresponding
// Zig type in src/protocol.zig). This proves the JSON Schema is faithful
// to the legacy Zig source without invoking a TS runtime.
// ============================================================================

test "AC1 round-trip: envelope schema requires the same fields as src/protocol.zig DreamBall" {
    const testing = std.testing;
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const io = std.Io.Threaded.global_single_threaded.io();

    const env_bytes = try std.Io.Dir.cwd().readFileAlloc(io, SCHEMA_ENVELOPE, arena, .limited(1 << 20));
    const env_v = try std.json.parseFromSliceLeaky(std.json.Value, arena, env_bytes, .{});

    // Required core fields per src/protocol.zig:DreamBall (the fields with
    // no default and no optional `?`).
    const required_core = [_][]const u8{
        "type", "format-version", "stage", "identity", "genesis-hash", "revision",
    };
    const required_arr = env_v.object.get("required") orelse return error.NoRequired;
    try testing.expect(required_arr == .array);
    try testing.expectEqual(@as(usize, required_core.len), required_arr.array.items.len);
    for (required_core, 0..) |name, i| {
        try testing.expectEqualStrings(name, required_arr.array.items[i].string);
    }

    // Optional properties present in src/protocol.zig:DreamBall must all
    // appear in the schema's `properties`. Fields not yet covered by the
    // spike (look/feel/act/contains/derived_from/identity_pq/dreamball_type/
    // field_kind/guilds) are deliberate omissions for the spike scope —
    // they're documented in docs/decisions/2026-04-28-codegen-spike-findings.md
    // §"Spike-scope omissions".
    const expected_optional = [_][]const u8{
        "name", "created", "updated", "note", "signatures",
        "sealed-payload-hash", "unlock-guild", "reveal-hint", "sealed-until",
    };
    const props = env_v.object.get("properties") orelse return error.NoProperties;
    try testing.expect(props == .object);
    for (expected_optional) |name| {
        if (props.object.get(name) == null) {
            std.debug.print("AC1: schema missing expected property '{s}'\n", .{name});
            return error.MissingProperty;
        }
    }
}

test "AC1 round-trip: SealedBody schema mirrors Relic struct" {
    const testing = std.testing;
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const io = std.Io.Threaded.global_single_threaded.io();

    const sb_bytes = try std.Io.Dir.cwd().readFileAlloc(io, SCHEMA_SEALED_BODY, arena, .limited(1 << 20));
    const sb_v = try std.json.parseFromSliceLeaky(std.json.Value, arena, sb_bytes, .{});

    const required_arr = sb_v.object.get("required") orelse return error.NoRequired;
    try testing.expect(required_arr == .array);
    try testing.expectEqual(@as(usize, 2), required_arr.array.items.len);
    try testing.expectEqualStrings("sealed-payload-hash", required_arr.array.items[0].string);
    try testing.expectEqualStrings("unlock-guild", required_arr.array.items[1].string);

    const props = sb_v.object.get("properties") orelse return error.NoProperties;
    for ([_][]const u8{ "reveal-hint", "sealed-until" }) |name| {
        if (props.object.get(name) == null) return error.MissingProperty;
    }
}

test "AC1 round-trip: SignatureTierWrapper schema mirrors Signature struct alg picklist" {
    const testing = std.testing;
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const io = std.Io.Threaded.global_single_threaded.io();

    const st_bytes = try std.Io.Dir.cwd().readFileAlloc(io, SCHEMA_SIGTIER, arena, .limited(1 << 20));
    const st_v = try std.json.parseFromSliceLeaky(std.json.Value, arena, st_bytes, .{});

    const props = st_v.object.get("properties") orelse return error.NoProperties;
    const alg = props.object.get("alg") orelse return error.NoAlgProperty;
    const alg_enum = alg.object.get("enum") orelse return error.AlgNoEnum;
    try testing.expect(alg_enum == .array);
    try testing.expectEqual(@as(usize, 2), alg_enum.array.items.len);
    try testing.expectEqualStrings("ed25519", alg_enum.array.items[0].string);
    try testing.expectEqualStrings("ml-dsa-87", alg_enum.array.items[1].string);
}
