//! Zig tool — emits TypeScript types + a minimal dCBOR encoder/decoder
//! matching the Zig side of the DreamBall protocol. Keeps the Svelte
//! library's wire-format knowledge in sync with the Zig protocol without
//! hand-maintaining duplicate schemas.
//!
//! Run from repo root:
//!   zig build schemagen
//! or
//!   bun run codegen
//!
//! Writes:
//!   src/lib/generated/types.ts
//!   src/lib/generated/cbor.ts
//!   src/lib/generated/README.md
//!
//! CLAUDE.md operating principle: the docs must explain WHY the generated
//! code is shaped the way it is — the generated README covers that.

const std = @import("std");

const TYPES_OUT = "src/lib/generated/types.ts";
const CBOR_OUT = "src/lib/generated/cbor.ts";
const SCHEMAS_OUT = "src/lib/generated/schemas.ts";
const README_OUT = "src/lib/generated/README.md";

const TYPES_SRC =
    \\// AUTO-GENERATED by tools/schema-gen — do not edit by hand.
    \\// Regenerate with `bun run codegen`.
    \\//
    \\// Types mirror the Zig protocol surface in src/protocol.zig +
    \\// src/protocol_v2.zig. The CBOR wire format is specified in
    \\// docs/PROTOCOL.md; the matching encoder/decoder lives in
    \\// ./cbor.ts.
    \\
    \\export type Base58 = `b58:${string}`;
    \\export type Fingerprint = Base58;    // 32 bytes, base58-encoded with "b58:" prefix
    \\export type Bytes32 = Base58;         // same shape; different semantic label
    \\
    \\export type DreamBallType =
    \\  | 'avatar'
    \\  | 'agent'
    \\  | 'tool'
    \\  | 'relic'
    \\  | 'field'
    \\  | 'guild';
    \\
    \\export type Stage = 'seed' | 'dreamball' | 'dragonball';
    \\
    \\export interface Signature {
    \\  alg: 'ed25519' | 'ml-dsa-87';
    \\  value: Base58;
    \\}
    \\
    \\export interface Asset {
    \\  'media-type': string;
    \\  hash: Bytes32;
    \\  url?: string[];
    \\  embedded?: Base58;
    \\  size?: number;
    \\  note?: string;
    \\}
    \\
    \\export interface Look {
    \\  asset?: Asset[];
    \\  preview?: Asset;
    \\  background?: string;
    \\  note?: string;
    \\}
    \\
    \\export interface Feel {
    \\  personality?: string;
    \\  voice?: string;
    \\  values?: string[];
    \\  tempo?: string;
    \\  note?: string;
    \\}
    \\
    \\export interface Skill {
    \\  name: string;
    \\  trigger?: string;
    \\  body?: string;
    \\  asset?: Asset;
    \\  requires?: string[];
    \\  note?: string;
    \\}
    \\
    \\export interface Act {
    \\  model?: string;
    \\  'system-prompt'?: string;
    \\  skill?: Skill[];
    \\  script?: Asset[];
    \\  tool?: string[];
    \\  note?: string;
    \\}
    \\
    \\// ===== v2 =====
    \\
    \\export interface MemoryNode {
    \\  id: number;
    \\  content?: string;
    \\  lookups?: Record<string, number>;
    \\  created?: string;       // RFC 3339
    \\  'last-recalled'?: string;
    \\}
    \\
    \\export type MemoryConnectionKind = 'semantic' | 'emotional' | 'temporal' | 'other';
    \\
    \\export interface MemoryConnection {
    \\  from: number;
    \\  to: number;
    \\  kind: MemoryConnectionKind;
    \\  strength?: number;
    \\  label?: string;
    \\}
    \\
    \\export interface Memory {
    \\  nodes: MemoryNode[];
    \\  connections: MemoryConnection[];
    \\  'last-updated'?: string;
    \\}
    \\
    \\export interface Triple {
    \\  from: string;
    \\  label: string;
    \\  to: string;
    \\}
    \\
    \\export interface KnowledgeGraph {
    \\  triples: Triple[];
    \\  source?: string;
    \\}
    \\
    \\export interface EmotionalAxis {
    \\  name: string;
    \\  value: number;
    \\  min?: number;
    \\  max?: number;
    \\}
    \\
    \\export interface EmotionalRegister {
    \\  axes: EmotionalAxis[];
    \\  'observed-at'?: string;
    \\}
    \\
    \\export type InteractionKind = 'speak' | 'listen' | 'act' | 'receive';
    \\
    \\export interface Interaction {
    \\  turn: number;
    \\  actor: Fingerprint;
    \\  kind: InteractionKind;
    \\  content?: string;
    \\  timestamp?: string;
    \\  outcome?: string;
    \\}
    \\
    \\export interface InteractionSet {
    \\  'set-id': Base58;
    \\  interactions: Interaction[];
    \\  created?: string;
    \\}
    \\
    \\export interface GuildPolicy {
    \\  public: string[];
    \\  'guild-only': string[];
    \\  'admin-only': string[];
    \\  note?: string;
    \\}
    \\
    \\export interface GuildMembership {
    \\  member: Fingerprint;
    \\  'is-admin'?: boolean;
    \\}
    \\
    \\export interface Guild {
    \\  'guild-name': string;
    \\  'keyspace-root-hash': Bytes32;
    \\  members: GuildMembership[];
    \\  policy?: GuildPolicy;
    \\}
    \\
    \\export interface Relic {
    \\  'sealed-payload-hash': Bytes32;
    \\  'unlock-guild': Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\}
    \\
    \\export interface Transmission {
    \\  'tool-fp': Fingerprint;
    \\  'target-fp': Fingerprint;
    \\  'via-guild': Fingerprint;
    \\  'sender-fp'?: Fingerprint;
    \\  'transmitted-at'?: string;
    \\  'tool-envelope': Base58;   // raw CBOR bytes, base58-wrapped
    \\  signatures?: Signature[];
    \\}
    \\
    \\export interface SecretRef {
    \\  name: string;
    \\  locator: string;
    \\  'issued-by'?: Fingerprint;
    \\  description?: string;
    \\}
    \\
    \\// ===== The top-level DreamBall =====
    \\
    \\export interface DreamBall {
    \\  type: 'jelly.dreamball' | `jelly.dreamball.${DreamBallType}`;
    \\  'format-version': 1 | 2;
    \\  stage: Stage;
    \\  identity: Fingerprint;       // the Ed25519 pubkey in b58
    \\  'genesis-hash': Bytes32;
    \\  revision: number;
    \\  name?: string;
    \\  created?: string;
    \\  updated?: string;
    \\  note?: string;
    \\  look?: Look;
    \\  feel?: Feel;
    \\  act?: Act;
    \\  memory?: Memory;
    \\  'knowledge-graph'?: KnowledgeGraph;
    \\  'emotional-register'?: EmotionalRegister;
    \\  'interaction-set'?: InteractionSet[];
    \\  guild?: Fingerprint[];        // Guild memberships
    \\  contains?: Fingerprint[];
    \\  'derived-from'?: Fingerprint[];
    \\  signatures?: Signature[];
    \\  // Guild-type specific
    \\  'guild-name'?: string;
    \\  'keyspace-root-hash'?: Bytes32;
    \\  member?: Fingerprint[];
    \\  admin?: Fingerprint[];
    \\  policy?: GuildPolicy;
    \\  // Relic-type specific
    \\  'sealed-payload-hash'?: Bytes32;
    \\  'unlock-guild'?: Fingerprint;
    \\  'reveal-hint'?: string;
    \\  'sealed-until'?: string;
    \\  // Tool-type specific
    \\  skill?: Skill;
    \\  'applicable-to'?: string[];
    \\  // Field-type specific
    \\  'omnispherical-grid'?: OmnisphericalGrid;
    \\  'ambient-palette'?: string[];
    \\  'dream-field-id'?: string;
    \\  // Agent-type specific
    \\  'personality-master-prompt'?: string;
    \\  secret?: SecretRef[];
    \\}
    \\
    \\export interface Vec3 {
    \\  x: number;
    \\  y: number;
    \\  z: number;
    \\}
    \\
    \\export interface CameraRing {
    \\  radius: number;
    \\  tilt: number;
    \\  fov: number;
    \\}
    \\
    \\export interface OmnisphericalGrid {
    \\  'pole-north'?: Vec3;
    \\  'pole-south'?: Vec3;
    \\  'camera-ring'?: CameraRing[];
    \\  'layer-depth'?: number;
    \\  resolution?: number;
    \\  note?: string;
    \\}
    \\
    \\/** Convenience: a DreamBall bundle (the .jelly file) — the envelope
    \\ *  plus optional attachments carried alongside (textures, scripts,
    \\ *  sealed payloads). For most consumers `DreamBall` alone is enough.
    \\ */
    \\export interface JellyBundle {
    \\  envelope: DreamBall;
    \\  attachments: Uint8Array[];
    \\  flags: {
    \\    compressed: boolean;
    \\    encrypted: boolean;
    \\    attachmentsEncrypted: boolean;
    \\  };
    \\  version: number;
    \\}
    \\
    \\export const FORMAT_VERSION = 1 as const;
    \\export const FORMAT_VERSION_V2 = 2 as const;
    \\
    \\export const DREAMBALL_TYPES: readonly DreamBallType[] = [
    \\  'avatar',
    \\  'agent',
    \\  'tool',
    \\  'relic',
    \\  'field',
    \\  'guild',
    \\] as const;
    \\
    \\// ===== §13 palace envelopes =====
    \\
    \\/** §13.1 field-kind open-enum attribute on jelly.dreamball.field. */
    \\export interface FieldKind {
    \\  value: string;
    \\}
    \\
    \\/** §13.2 jelly.layout — spatial arrangement of child DreamBalls. */
    \\export interface Placement {
    \\  'child-fp': Bytes32;
    \\  position: [number, number, number];
    \\  facing: [number, number, number, number];  // quaternion [qx, qy, qz, qw]
    \\}
    \\
    \\export interface Layout {
    \\  type: 'jelly.layout';
    \\  'format-version': 2;
    \\  placements: Placement[];
    \\  note?: string;
    \\}
    \\
    \\/** §13.3 jelly.timeline — DAG head-hashes for a palace. */
    \\export interface Timeline {
    \\  type: 'jelly.timeline';
    \\  'format-version': 3;
    \\  'palace-fp': Bytes32;
    \\  'head-hashes': Bytes32[];
    \\  note?: string;
    \\}
    \\
    \\export type ActionKind =
    \\  | 'palace-minted'
    \\  | 'room-added'
    \\  | 'avatar-inscribed'
    \\  | 'aqueduct-created'
    \\  | 'move'
    \\  | 'true-naming'
    \\  | 'inscription-updated'
    \\  | 'inscription-orphaned'
    \\  | 'inscription-pending-embedding';
    \\
    \\/** §13.3 jelly.action — a single DAG node in a palace timeline. */
    \\export interface Action {
    \\  type: 'jelly.action';
    \\  'format-version': 3;
    \\  'action-kind': ActionKind;
    \\  actor: Bytes32;
    \\  'parent-hashes': Bytes32[];
    \\  'target-fp'?: Bytes32;
    \\  timestamp?: number;
    \\  deps?: Bytes32[];
    \\  nacks?: Bytes32[];
    \\}
    \\
    \\export type AqueductPhase = 'in' | 'out' | 'standing' | 'resonant';
    \\
    \\/** §13.4 jelly.aqueduct — directed channel between two DreamBalls. */
    \\export interface Aqueduct {
    \\  type: 'jelly.aqueduct';
    \\  'format-version': 2;
    \\  from: Bytes32;
    \\  to: Bytes32;
    \\  kind: string;   // open-enum: "gaze" | "visit" | "transmit" | …
    \\  capacity: number;
    \\  strength: number;
    \\  resistance: number;
    \\  capacitance: number;
    \\  conductance?: number;
    \\  phase?: AqueductPhase;
    \\  'last-traversed'?: number;
    \\}
    \\
    \\/** §13.5 jelly.element-tag — elemental affinity attribute. */
    \\export interface ElementTag {
    \\  type: 'jelly.element-tag';
    \\  'format-version': 2;
    \\  element: string;   // open-enum: "wood" | "fire" | "earth" | "metal" | "water" | …
    \\  phase?: string;    // open-enum: "nourishing" | "destruction" | "yin" | "yang" | …
    \\  note?: string;
    \\}
    \\
    \\/** §13.6 jelly.trust-observation — multi-axis trust record. */
    \\export interface TrustAxis {
    \\  name: string;
    \\  value: number;
    \\  range: [number, number];
    \\}
    \\
    \\export interface TrustObservation {
    \\  type: 'jelly.trust-observation';
    \\  'format-version': 2;
    \\  observer: Bytes32;
    \\  about: Bytes32;
    \\  axes?: TrustAxis[];
    \\  'observed-at'?: number;
    \\  context?: string;
    \\  signatures?: Signature[];
    \\}
    \\
    \\/** §13.7 jelly.inscription — text/content attached to a room. */
    \\export interface Inscription {
    \\  type: 'jelly.inscription';
    \\  'format-version': 2;
    \\  surface: string;     // open-enum: "scroll" | "tablet" | "book-spread" | "etched-wall" | …
    \\  placement: string;   // "auto" | "curator"
    \\  note?: string;
    \\}
    \\
    \\/** §13.8 jelly.mythos — poetic or canonical naming chain. */
    \\export interface Mythos {
    \\  type: 'jelly.mythos';
    \\  'format-version': 2;
    \\  'is-genesis': boolean;
    \\  predecessor?: Bytes32;
    \\  about?: Bytes32;
    \\  form?: string;      // open-enum: "blurb" | "invocation" | "image" | "utterance" | "glyph" | "true-name" | …
    \\  body?: string;
    \\  'true-name'?: string;
    \\  'discovered-in'?: Bytes32;
    \\  synthesizes?: Bytes32[];
    \\  'inspired-by'?: Bytes32[];
    \\  author?: Bytes32;
    \\  'authored-at'?: number;
    \\}
    \\
    \\/** §13.9 jelly.archiform — room archetype/template. */
    \\export interface Archiform {
    \\  type: 'jelly.archiform';
    \\  'format-version': 2;
    \\  form: string;        // open-enum: "library" | "forge" | "throne-room" | …
    \\  tradition?: string;  // open-enum: "hermetic" | "shinto" | "vedic" | "computational" | "none" | …
    \\  'parent-form'?: string;
    \\  note?: string;
    \\}
    \\
    \\// DO NOT EDIT — generated by tools/schema-gen/main.zig
    \\
;

const CBOR_SRC =
    \\// AUTO-GENERATED by tools/schema-gen — do not edit by hand.
    \\// Regenerate with `bun run codegen`.
    \\//
    \\// Minimal dCBOR decoder. Matches the subset emitted by the Zig
    \\// encoder in src/envelope.zig: tags 200 (envelope) / 201 (leaf) /
    \\// 1 (epoch time), canonical map-key ordering, smallest-int form,
    \\// text/bytes/array/map/uint/f64. Floats only appear inside the
    \\// jelly.omnispherical-grid / jelly.memory / jelly.emotional-register
    \\// envelopes — see docs/PROTOCOL.md §12.2.
    \\//
    \\// For v2 MVP we only need decode (incoming .jelly files from the
    \\// jelly-server). Encode path stays on the Zig side.
    \\
    \\export const TAG_EPOCH = 1;
    \\export const TAG_ENVELOPE = 200;
    \\export const TAG_LEAF = 201;
    \\
    \\export class CborReader {
    \\  private cursor = 0;
    \\  constructor(private readonly bytes: Uint8Array) {}
    \\
    \\  atEnd(): boolean {
    \\    return this.cursor >= this.bytes.length;
    \\  }
    \\
    \\  private takeByte(): number {
    \\    if (this.cursor >= this.bytes.length) throw new Error('cbor: truncated');
    \\    return this.bytes[this.cursor++];
    \\  }
    \\
    \\  private readHead(): { major: number; arg: number | bigint; info: number } {
    \\    const b = this.takeByte();
    \\    const major = b >> 5;
    \\    const info = b & 0x1f;
    \\    if (info < 24) return { major, arg: info, info };
    \\    if (info === 24) {
    \\      const v = this.takeByte();
    \\      if (major !== 7 && v < 24) throw new Error('cbor: non-canonical integer (info 24, value < 24)');
    \\      return { major, arg: v, info };
    \\    }
    \\    if (info === 25) {
    \\      const hi = this.takeByte();
    \\      const lo = this.takeByte();
    \\      const v = (hi << 8) | lo;
    \\      if (major !== 7 && v < 256) throw new Error('cbor: non-canonical integer (info 25, value < 256)');
    \\      return { major, arg: v, info };
    \\    }
    \\    if (info === 26) {
    \\      let v = 0;
    \\      for (let i = 0; i < 4; i++) v = (v << 8) | this.takeByte();
    \\      v = v >>> 0;
    \\      if (major !== 7 && v < 0x10000) throw new Error('cbor: non-canonical integer (info 26, value < 65536)');
    \\      return { major, arg: v, info };
    \\    }
    \\    if (info === 27) {
    \\      let v = 0n;
    \\      for (let i = 0; i < 8; i++) v = (v << 8n) | BigInt(this.takeByte());
    \\      if (major !== 7 && v < 0x100000000n) throw new Error('cbor: non-canonical integer (info 27, value < 2^32)');
    \\      return { major, arg: v, info };
    \\    }
    \\    throw new Error(`cbor: unsupported info ${info}`);
    \\  }
    \\
    \\  readAny(): unknown {
    \\    const { major, arg, info } = this.readHead();
    \\    switch (major) {
    \\      case 0: return typeof arg === 'bigint' ? arg : arg;
    \\      case 1: return typeof arg === 'bigint' ? -(arg + 1n) : -(arg + 1);
    \\      case 2: return this.readByteString(Number(arg));
    \\      case 3: return this.readTextString(Number(arg));
    \\      case 4: {
    \\        const len = Number(arg);
    \\        const out: unknown[] = [];
    \\        for (let i = 0; i < len; i++) out.push(this.readAny());
    \\        return out;
    \\      }
    \\      case 5: {
    \\        const len = Number(arg);
    \\        const out: Record<string, unknown> = {};
    \\        for (let i = 0; i < len; i++) {
    \\          const k = this.readAny();
    \\          const v = this.readAny();
    \\          if (typeof k !== 'string') throw new Error('cbor: map key must be text');
    \\          out[k] = v;
    \\        }
    \\        return out;
    \\      }
    \\      case 6: {
    \\        const inner = this.readAny();
    \\        return { __cborTag: Number(arg), value: inner };
    \\      }
    \\      case 7: {
    \\        if (arg === 20) return false;
    \\        if (arg === 21) return true;
    \\        if (arg === 22) return null;
    \\        if (arg === 23) return undefined;
    \\        if (info === 25) {
    \\          // float16 — decode IEEE 754 half-precision
    \\          const bits = arg as number;
    \\          const exp = (bits >> 10) & 0x1f;
    \\          const frac = bits & 0x3ff;
    \\          const sign = (bits >> 15) ? -1 : 1;
    \\          if (exp === 0) return sign * Math.pow(2, -14) * (frac / 1024);
    \\          if (exp === 31) return frac ? NaN : sign * Infinity;
    \\          return sign * Math.pow(2, exp - 15) * (1 + frac / 1024);
    \\        }
    \\        if (info === 26) {
    \\          // float32 — decode via DataView
    \\          const buf = new ArrayBuffer(4);
    \\          const view = new DataView(buf);
    \\          view.setUint32(0, arg as number);
    \\          return view.getFloat32(0);
    \\        }
    \\        if (typeof arg === 'bigint') {
    \\          // float64 (info 27)
    \\          const buf = new ArrayBuffer(8);
    \\          const view = new DataView(buf);
    \\          view.setBigUint64(0, arg);
    \\          return view.getFloat64(0);
    \\        }
    \\        throw new Error(`cbor: unsupported simple ${arg}`);
    \\      }
    \\      default:
    \\        throw new Error(`cbor: unsupported major ${major}`);
    \\    }
    \\  }
    \\
    \\  private readByteString(len: number): Uint8Array {
    \\    if (this.cursor + len > this.bytes.length) throw new Error('cbor: truncated');
    \\    const out = this.bytes.slice(this.cursor, this.cursor + len);
    \\    this.cursor += len;
    \\    return out;
    \\  }
    \\
    \\  private readTextString(len: number): string {
    \\    const slice = this.readByteString(len);
    \\    return new TextDecoder().decode(slice);
    \\  }
    \\}
    \\
    \\/** Decode a .jelly envelope's top-level structure into a
    \\ *  human-readable JS object. Preserves CBOR tags via `__cborTag`
    \\ *  wrappers so callers can introspect envelope/leaf boundaries.
    \\ */
    \\export function decodeEnvelope(bytes: Uint8Array): unknown {
    \\  const reader = new CborReader(bytes);
    \\  return reader.readAny();
    \\}
    \\
    \\/** Convert bytes to the "b58:..." string used in the JSON export. */
    \\export function toBase58Tagged(bytes: Uint8Array): `b58:${string}` {
    \\  return `b58:${base58Encode(bytes)}`;
    \\}
    \\
    \\/** Bitcoin base58 — sufficient for protocol-adjacent short strings. */
    \\export function base58Encode(bytes: Uint8Array): string {
    \\  const alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
    \\  if (bytes.length === 0) return '';
    \\  let leadingZeros = 0;
    \\  while (leadingZeros < bytes.length && bytes[leadingZeros] === 0) leadingZeros++;
    \\  let digits: number[] = [];
    \\  for (const b of bytes) {
    \\    let carry = b;
    \\    for (let i = 0; i < digits.length; i++) {
    \\      carry += digits[i] * 256;
    \\      digits[i] = carry % 58;
    \\      carry = Math.floor(carry / 58);
    \\    }
    \\    while (carry) {
    \\      digits.push(carry % 58);
    \\      carry = Math.floor(carry / 58);
    \\    }
    \\  }
    \\  let out = '1'.repeat(leadingZeros);
    \\  for (let i = digits.length - 1; i >= 0; i--) out += alphabet[digits[i]];
    \\  return out;
    \\}
    \\
    \\export function base58Decode(s: string): Uint8Array {
    \\  const alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
    \\  if (s.length === 0) return new Uint8Array();
    \\  let leadingOnes = 0;
    \\  while (leadingOnes < s.length && s[leadingOnes] === '1') leadingOnes++;
    \\  const bytes: number[] = [];
    \\  for (const ch of s) {
    \\    let carry = alphabet.indexOf(ch);
    \\    if (carry < 0) throw new Error(`base58: invalid char '${ch}'`);
    \\    for (let i = 0; i < bytes.length; i++) {
    \\      carry += bytes[i] * 58;
    \\      bytes[i] = carry & 0xff;
    \\      carry >>= 8;
    \\    }
    \\    while (carry) {
    \\      bytes.push(carry & 0xff);
    \\      carry >>= 8;
    \\    }
    \\  }
    \\  const out = new Uint8Array(leadingOnes + bytes.length);
    \\  for (let i = 0; i < bytes.length; i++) out[leadingOnes + i] = bytes[bytes.length - 1 - i];
    \\  return out;
    \\}
    \\
    \\/** Decode a Base58Tagged value ("b58:...") back to bytes. */
    \\export function fromBase58Tagged(s: string): Uint8Array {
    \\  if (!s.startsWith('b58:')) throw new Error(`expected b58: prefix, got '${s.slice(0, 8)}...'`);
    \\  return base58Decode(s.slice(4));
    \\}
    \\
    \\// ========================================================================
    \\// §13 palace envelope typed decoders
    \\// ========================================================================
    \\
    \\import type {
    \\  Layout, Timeline, Action, Aqueduct,
    \\  ElementTag, TrustObservation, Inscription, Mythos, Archiform
    \\} from './types.js';
    \\
    \\/** Walk the raw CBOR tree and extract the core map + attribute list. */
    \\function extractEnvelopeParts(raw: unknown): {
    \\  core: Record<string, unknown>;
    \\  attrs: [string, unknown][];
    \\} {
    \\  const env = raw as { __cborTag: number; value: unknown };
    \\  if (env.__cborTag !== 200) throw new Error('expected tag 200 envelope');
    \\  const arr = env.value as unknown[];
    \\  // First element is tag-201 leaf (core map), rest are [label, value] attribute pairs.
    \\  const leafRaw = arr[0] as { __cborTag: number; value: unknown };
    \\  if (leafRaw.__cborTag !== 201) throw new Error('expected tag 201 leaf');
    \\  const core = leafRaw.value as Record<string, unknown>;
    \\  const attrs: [string, unknown][] = [];
    \\  for (let i = 1; i < arr.length; i++) {
    \\    const pair = arr[i] as unknown[];
    \\    attrs.push([pair[0] as string, pair[1]]);
    \\  }
    \\  return { core, attrs };
    \\}
    \\
    \\function b58Bytes(raw: unknown): `b58:${string}` {
    \\  return toBase58Tagged(raw as Uint8Array);
    \\}
    \\
    \\/** Decode a jelly.layout CBOR envelope. */
    \\export function decodeLayout(bytes: Uint8Array): Layout {
    \\  const { core, attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  void core; // type/format-version checked implicitly
    \\  const placements: Layout['placements'] = [];
    \\  let note: string | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'placement') {
    \\      const m = v as Record<string, unknown>;
    \\      const pos = m['position'] as number[];
    \\      const fac = m['facing'] as number[];
    \\      placements.push({
    \\        'child-fp': b58Bytes(m['child-fp']),
    \\        position: [pos[0], pos[1], pos[2]],
    \\        facing: [fac[0], fac[1], fac[2], fac[3]],
    \\      });
    \\    } else if (k === 'note') { note = v as string; }
    \\  }
    \\  return { type: 'jelly.layout', 'format-version': 2, placements, note };
    \\}
    \\
    \\/** Decode a jelly.timeline CBOR envelope. */
    \\export function decodeTimeline(bytes: Uint8Array): Timeline {
    \\  const { core, attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  const palaceFp = b58Bytes(core['palace-fp']);
    \\  const headHashes: `b58:${string}`[] = [];
    \\  let note: string | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'head-hashes') headHashes.push(b58Bytes(v));
    \\    else if (k === 'note') note = v as string;
    \\  }
    \\  return { type: 'jelly.timeline', 'format-version': 3, 'palace-fp': palaceFp, 'head-hashes': headHashes, note };
    \\}
    \\
    \\/** Decode a jelly.action CBOR envelope. */
    \\export function decodeAction(bytes: Uint8Array): Action {
    \\  const { core, attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  // action-kind, actor, parent-hashes are in the core map.
    \\  const actionKind = core['action-kind'] as Action['action-kind'];
    \\  const actor = b58Bytes(core['actor']);
    \\  // parent-hashes is a CBOR array in the core map.
    \\  const parentHashRaw = core['parent-hashes'] as Uint8Array[];
    \\  const parentHashes: `b58:${string}`[] = Array.isArray(parentHashRaw)
    \\    ? parentHashRaw.map(b58Bytes)
    \\    : [];
    \\  const deps: `b58:${string}`[] = [];
    \\  const nacks: `b58:${string}`[] = [];
    \\  let targetFp: `b58:${string}` | undefined;
    \\  let timestamp: number | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'target-fp') targetFp = b58Bytes(v);
    \\    else if (k === 'timestamp') {
    \\      const tagged = v as { __cborTag?: number; value?: unknown };
    \\      timestamp = (tagged.__cborTag === 1 ? tagged.value : v) as number;
    \\    }
    \\    else if (k === 'deps') deps.push(b58Bytes(v));
    \\    else if (k === 'nacks') nacks.push(b58Bytes(v));
    \\  }
    \\  const out: Action = {
    \\    type: 'jelly.action', 'format-version': 3,
    \\    'action-kind': actionKind, actor, 'parent-hashes': parentHashes
    \\  };
    \\  if (targetFp !== undefined) out['target-fp'] = targetFp;
    \\  if (timestamp !== undefined) out.timestamp = timestamp;
    \\  if (deps.length > 0) out.deps = deps;
    \\  if (nacks.length > 0) out.nacks = nacks;
    \\  return out;
    \\}
    \\
    \\/** Decode a jelly.aqueduct CBOR envelope. */
    \\export function decodeAqueduct(bytes: Uint8Array): Aqueduct {
    \\  const { core, attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  // from, to, kind are in the core map; all numeric fields are attributes.
    \\  const from = b58Bytes(core['from']);
    \\  const to = b58Bytes(core['to']);
    \\  const kind = core['kind'] as string;
    \\  let capacity: number | undefined;
    \\  let strength: number | undefined;
    \\  let resistance: number | undefined;
    \\  let capacitance: number | undefined;
    \\  let conductance: number | undefined;
    \\  let phase: Aqueduct['phase'];
    \\  let lastTraversed: number | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'capacity') capacity = v as number;
    \\    else if (k === 'strength') strength = v as number;
    \\    else if (k === 'resistance') resistance = v as number;
    \\    else if (k === 'capacitance') capacitance = v as number;
    \\    else if (k === 'conductance') conductance = v as number;
    \\    else if (k === 'phase') phase = v as Aqueduct['phase'];
    \\    else if (k === 'last-traversed') {
    \\      // epoch-time tag wrapper — extract inner value
    \\      const tagged = v as { __cborTag?: number; value?: unknown };
    \\      lastTraversed = (tagged.__cborTag === 1 ? tagged.value : v) as number;
    \\    }
    \\  }
    \\  if (capacity === undefined || strength === undefined || resistance === undefined || capacitance === undefined) {
    \\    throw new Error('decodeAqueduct: missing required numeric attribute');
    \\  }
    \\  const out: Aqueduct = {
    \\    type: 'jelly.aqueduct', 'format-version': 2,
    \\    from, to, kind, capacity, strength, resistance, capacitance
    \\  };
    \\  if (conductance !== undefined) out.conductance = conductance;
    \\  if (phase !== undefined) out.phase = phase;
    \\  if (lastTraversed !== undefined) out['last-traversed'] = lastTraversed;
    \\  return out;
    \\}
    \\
    \\/** Decode a jelly.element-tag CBOR envelope. */
    \\export function decodeElementTag(bytes: Uint8Array): ElementTag {
    \\  const { attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  let element: string | undefined;
    \\  let phase: string | undefined;
    \\  let note: string | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'element') element = v as string;
    \\    else if (k === 'phase') phase = v as string;
    \\    else if (k === 'note') note = v as string;
    \\  }
    \\  if (element === undefined) throw new Error('decodeElementTag: missing element attribute');
    \\  const out: ElementTag = { type: 'jelly.element-tag', 'format-version': 2, element };
    \\  if (phase !== undefined) out.phase = phase;
    \\  if (note !== undefined) out.note = note;
    \\  return out;
    \\}
    \\
    \\/** Decode a jelly.trust-observation CBOR envelope. */
    \\export function decodeTrustObservation(bytes: Uint8Array): TrustObservation {
    \\  const { core, attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  const observer = b58Bytes(core['observer']);
    \\  const about = b58Bytes(core['about']);
    \\  const axes: TrustObservation['axes'] = [];
    \\  const signatures: TrustObservation['signatures'] = [];
    \\  let observedAt: number | undefined;
    \\  let context: string | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'axis') {
    \\      const m = v as Record<string, unknown>;
    \\      axes!.push({
    \\        name: m['name'] as string,
    \\        value: m['value'] as number,
    \\        range: m['range'] as [number, number],
    \\      });
    \\    } else if (k === 'observed-at') { observedAt = v as number; }
    \\    else if (k === 'context') { context = v as string; }
    \\    else if (k === 'signed') {
    \\      const pair = v as unknown[];
    \\      signatures!.push({ alg: pair[0] as 'ed25519' | 'ml-dsa-87', value: b58Bytes(pair[1]) });
    \\    }
    \\  }
    \\  const out: TrustObservation = { type: 'jelly.trust-observation', 'format-version': 2, observer, about };
    \\  if (axes.length > 0) out.axes = axes;
    \\  if (observedAt !== undefined) out['observed-at'] = observedAt;
    \\  if (context !== undefined) out.context = context;
    \\  if (signatures!.length > 0) out.signatures = signatures;
    \\  return out;
    \\}
    \\
    \\/** Decode a jelly.inscription CBOR envelope. */
    \\export function decodeInscription(bytes: Uint8Array): Inscription {
    \\  const { attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  let surface: string | undefined;
    \\  let placement = 'auto';
    \\  let note: string | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'surface') surface = v as string;
    \\    else if (k === 'placement') placement = v as string;
    \\    else if (k === 'note') note = v as string;
    \\  }
    \\  if (surface === undefined) throw new Error('decodeInscription: missing surface attribute');
    \\  const out: Inscription = { type: 'jelly.inscription', 'format-version': 2, surface, placement };
    \\  if (note !== undefined) out.note = note;
    \\  return out;
    \\}
    \\
    \\/** Decode a jelly.mythos CBOR envelope. */
    \\export function decodeMythos(bytes: Uint8Array): Mythos {
    \\  const { core, attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  const isGenesis = core['is-genesis'] as boolean;
    \\  let predecessor: `b58:${string}` | undefined;
    \\  let about: `b58:${string}` | undefined;
    \\  let form: string | undefined;
    \\  let body: string | undefined;
    \\  let trueName: string | undefined;
    \\  let discoveredIn: `b58:${string}` | undefined;
    \\  const synthesizes: `b58:${string}`[] = [];
    \\  const inspiredBy: `b58:${string}`[] = [];
    \\  let author: `b58:${string}` | undefined;
    \\  let authoredAt: number | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'predecessor') predecessor = b58Bytes(v);
    \\    else if (k === 'about') about = b58Bytes(v);
    \\    else if (k === 'form') form = v as string;
    \\    else if (k === 'body') body = v as string;
    \\    else if (k === 'true-name') trueName = v as string;
    \\    else if (k === 'discovered-in') discoveredIn = b58Bytes(v);
    \\    else if (k === 'synthesizes') synthesizes.push(b58Bytes(v));
    \\    else if (k === 'inspired-by') inspiredBy.push(b58Bytes(v));
    \\    else if (k === 'author') author = b58Bytes(v);
    \\    else if (k === 'authored-at') {
    \\      const tagged = v as { __cborTag?: number; value?: unknown };
    \\      authoredAt = (tagged.__cborTag === 1 ? tagged.value : v) as number;
    \\    }
    \\  }
    \\  const out: Mythos = { type: 'jelly.mythos', 'format-version': 2, 'is-genesis': isGenesis };
    \\  if (predecessor !== undefined) out.predecessor = predecessor;
    \\  if (about !== undefined) out.about = about;
    \\  if (form !== undefined) out.form = form;
    \\  if (body !== undefined) out.body = body;
    \\  if (trueName !== undefined) out['true-name'] = trueName;
    \\  if (discoveredIn !== undefined) out['discovered-in'] = discoveredIn;
    \\  if (synthesizes.length > 0) out.synthesizes = synthesizes;
    \\  if (inspiredBy.length > 0) out['inspired-by'] = inspiredBy;
    \\  if (author !== undefined) out.author = author;
    \\  if (authoredAt !== undefined) out['authored-at'] = authoredAt;
    \\  return out;
    \\}
    \\
    \\/** Decode a jelly.archiform CBOR envelope. */
    \\export function decodeArchiform(bytes: Uint8Array): Archiform {
    \\  const { attrs } = extractEnvelopeParts(decodeEnvelope(bytes));
    \\  let form: string | undefined;
    \\  let tradition: string | undefined;
    \\  let parentForm: string | undefined;
    \\  let note: string | undefined;
    \\  for (const [k, v] of attrs) {
    \\    if (k === 'form') form = v as string;
    \\    else if (k === 'tradition') tradition = v as string;
    \\    else if (k === 'parent-form') parentForm = v as string;
    \\    else if (k === 'note') note = v as string;
    \\  }
    \\  if (form === undefined) throw new Error('decodeArchiform: missing form attribute');
    \\  const out: Archiform = { type: 'jelly.archiform', 'format-version': 2, form };
    \\  if (tradition !== undefined) out.tradition = tradition;
    \\  if (parentForm !== undefined) out['parent-form'] = parentForm;
    \\  if (note !== undefined) out.note = note;
    \\  return out;
    \\}
    \\
    \\// DO NOT EDIT — generated by tools/schema-gen/main.zig
    \\
;

const README_SRC =
    \\# `src/lib/generated/`
    \\
    \\Every file in this directory is **generated** by `tools/schema-gen`.
    \\Do not edit by hand — changes will be overwritten by
    \\`bun run codegen` or `zig build schemagen`.
    \\
    \\## What lives here
    \\
    \\- `types.ts` — TypeScript interfaces mirroring the Zig protocol
    \\  surface (`src/protocol.zig` + `src/protocol_v2.zig`). These drive
    \\  the renderer library and the showcase app's type-safety story.
    \\- `cbor.ts` — minimal dCBOR decoder + base58 helpers for consuming
    \\  `.jelly` bytes when the lib receives them directly (vs. going
    \\  through the `jelly-server` HTTP shim which returns JSON).
    \\
    \\## Why it's generated, not hand-written
    \\
    \\The Zig side is the canonical source of truth for the wire format.
    \\Hand-maintaining a parallel TypeScript schema drifts the moment the
    \\protocol ships a new envelope — see the MTG-style type taxonomy
    \\in `docs/VISION.md §10`, which added six types in a single sprint.
    \\
    \\The generator is a Zig program so it can (in future) introspect
    \\the actual `src/protocol.zig` structs via comptime reflection.
    \\For this first cut the schema is hard-coded inside
    \\`tools/schema-gen/main.zig` — change it there, re-run `bun run
    \\codegen`, commit the updated outputs.
    \\
    \\## Why types.ts uses string literals for `type` discriminants
    \\
    \\The CBOR core carries `type: "jelly.dreamball.avatar"` (etc.).
    \\Mirroring that as a string literal type in TypeScript means the
    \\compiler can narrow on `ball.type === 'jelly.dreamball.avatar'`
    \\and give you the right attribute surface for that variant. The
    \\short-tag form (`'avatar' | 'agent' | ...`) also appears as
    \\`DreamBallType` for CLI-adjacent UIs.
    \\
    \\## Why floats show up in cbor.ts
    \\
    \\v1's protocol disallows floats. v2 carves out one exception for
    \\spatial data (omnispherical grids, emotional axes) — see
    \\`docs/PROTOCOL.md §12.2`. The CBOR decoder must handle
    \\IEEE-754 float64 values (major type 7, info 27) so that these
    \\envelopes round-trip.
    \\
;

const SCHEMAS_SRC =
    \\// AUTO-GENERATED by tools/schema-gen — do not edit by hand.
    \\// Regenerate with `bun run codegen`.
    \\//
    \\// Valibot runtime validators for the DreamBall v2 protocol. Matches
    \\// one-to-one the interfaces in `./types.ts`. Use these to validate
    \\// JSON that came in from the wire (e.g., from the WASM parser or
    \\// an HTTP response). Typed results via `v.InferOutput<typeof X>`.
    \\//
    \\// Two entry-points worth knowing:
    \\//   - DreamBallSchema      — top-level; discriminates on `type`
    \\//   - ParseResult<T>       — tagged { success: true, data } | {
    \\//                            success: false, issues }
    \\
    \\import * as v from 'valibot';
    \\import type { InferOutput } from 'valibot';
    \\
    \\// ========================================================================
    \\// Primitives
    \\// ========================================================================
    \\
    \\/** Base58-wrapped bytes — the protocol's canonical form for 32-byte
    \\ *  identity / hash / fingerprint fields in JSON. */
    \\export const Base58Schema = v.pipe(
    \\  v.string(),
    \\  v.regex(/^b58:[1-9A-HJ-NP-Za-km-z]*$/, 'expected "b58:..." prefix')
    \\);
    \\
    \\export const Rfc3339Schema = v.pipe(
    \\  v.string(),
    \\  v.regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/, 'expected RFC3339 UTC')
    \\);
    \\
    \\export const SignatureAlgSchema = v.picklist(['ed25519', 'ml-dsa-87']);
    \\
    \\export const SignatureSchema = v.object({
    \\  alg: SignatureAlgSchema,
    \\  value: Base58Schema
    \\});
    \\
    \\// ========================================================================
    \\// v1 nested — look / feel / act / asset / skill
    \\// ========================================================================
    \\
    \\export const AssetSchema = v.object({
    \\  'media-type': v.string(),
    \\  hash: Base58Schema,
    \\  url: v.optional(v.array(v.string())),
    \\  embedded: v.optional(Base58Schema),
    \\  size: v.optional(v.number()),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const LookSchema = v.object({
    \\  asset: v.optional(v.array(AssetSchema)),
    \\  preview: v.optional(AssetSchema),
    \\  background: v.optional(v.string()),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const FeelSchema = v.object({
    \\  personality: v.optional(v.string()),
    \\  voice: v.optional(v.string()),
    \\  values: v.optional(v.array(v.string())),
    \\  tempo: v.optional(v.string()),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const SkillSchema = v.object({
    \\  name: v.string(),
    \\  trigger: v.optional(v.string()),
    \\  body: v.optional(v.string()),
    \\  asset: v.optional(AssetSchema),
    \\  requires: v.optional(v.array(v.string())),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const ActSchema = v.object({
    \\  model: v.optional(v.string()),
    \\  'system-prompt': v.optional(v.string()),
    \\  skill: v.optional(v.array(SkillSchema)),
    \\  script: v.optional(v.array(AssetSchema)),
    \\  tool: v.optional(v.array(v.string())),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\// ========================================================================
    \\// v2 agent slots — memory / knowledge-graph / emotional-register /
    \\//                  interaction-set
    \\// ========================================================================
    \\
    \\export const MemoryConnectionKindSchema = v.picklist(['semantic', 'emotional', 'temporal', 'other']);
    \\
    \\export const MemoryNodeSchema = v.object({
    \\  id: v.number(),
    \\  content: v.optional(v.string()),
    \\  lookups: v.optional(v.record(v.string(), v.number())),
    \\  created: v.optional(Rfc3339Schema),
    \\  'last-recalled': v.optional(Rfc3339Schema)
    \\});
    \\
    \\export const MemoryConnectionSchema = v.object({
    \\  from: v.number(),
    \\  to: v.number(),
    \\  kind: MemoryConnectionKindSchema,
    \\  strength: v.optional(v.number()),
    \\  label: v.optional(v.string())
    \\});
    \\
    \\export const MemorySchema = v.object({
    \\  nodes: v.array(MemoryNodeSchema),
    \\  connections: v.array(MemoryConnectionSchema),
    \\  'last-updated': v.optional(Rfc3339Schema)
    \\});
    \\
    \\export const TripleSchema = v.object({
    \\  from: v.string(),
    \\  label: v.string(),
    \\  to: v.string()
    \\});
    \\
    \\export const KnowledgeGraphSchema = v.object({
    \\  triples: v.array(TripleSchema),
    \\  source: v.optional(v.string())
    \\});
    \\
    \\export const EmotionalAxisSchema = v.object({
    \\  name: v.string(),
    \\  value: v.number(),
    \\  min: v.optional(v.number()),
    \\  max: v.optional(v.number())
    \\});
    \\
    \\export const EmotionalRegisterSchema = v.object({
    \\  axes: v.array(EmotionalAxisSchema),
    \\  'observed-at': v.optional(Rfc3339Schema)
    \\});
    \\
    \\export const InteractionKindSchema = v.picklist(['speak', 'listen', 'act', 'receive']);
    \\
    \\export const InteractionSchema = v.object({
    \\  turn: v.number(),
    \\  actor: Base58Schema,
    \\  kind: InteractionKindSchema,
    \\  content: v.optional(v.string()),
    \\  timestamp: v.optional(Rfc3339Schema),
    \\  outcome: v.optional(v.string())
    \\});
    \\
    \\export const InteractionSetSchema = v.object({
    \\  'set-id': Base58Schema,
    \\  interactions: v.array(InteractionSchema),
    \\  created: v.optional(Rfc3339Schema)
    \\});
    \\
    \\// ========================================================================
    \\// Guild / Relic / secrets / omnispherical grid
    \\// ========================================================================
    \\
    \\export const GuildPolicySchema = v.object({
    \\  public: v.array(v.string()),
    \\  'guild-only': v.array(v.string()),
    \\  'admin-only': v.array(v.string()),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const GuildMembershipSchema = v.object({
    \\  member: Base58Schema,
    \\  'is-admin': v.optional(v.boolean())
    \\});
    \\
    \\export const Vec3Schema = v.object({
    \\  x: v.number(),
    \\  y: v.number(),
    \\  z: v.number()
    \\});
    \\
    \\export const CameraRingSchema = v.object({
    \\  radius: v.number(),
    \\  tilt: v.number(),
    \\  fov: v.number()
    \\});
    \\
    \\export const OmnisphericalGridSchema = v.object({
    \\  'pole-north': v.optional(Vec3Schema),
    \\  'pole-south': v.optional(Vec3Schema),
    \\  'camera-ring': v.optional(v.array(CameraRingSchema)),
    \\  'layer-depth': v.optional(v.number()),
    \\  resolution: v.optional(v.number()),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const SecretRefSchema = v.object({
    \\  name: v.string(),
    \\  locator: v.string(),
    \\  'issued-by': v.optional(Base58Schema),
    \\  description: v.optional(v.string())
    \\});
    \\
    \\// ========================================================================
    \\// DreamBall — common core fields, then per-type variants
    \\// ========================================================================
    \\
    \\const commonCore = {
    \\  stage: v.picklist(['seed', 'dreamball', 'dragonball']),
    \\  identity: Base58Schema,
    \\  'genesis-hash': Base58Schema,
    \\  revision: v.number(),
    \\  'format-version': v.union([v.literal(1), v.literal(2)]),
    \\  name: v.optional(v.string()),
    \\  created: v.optional(Rfc3339Schema),
    \\  updated: v.optional(Rfc3339Schema),
    \\  note: v.optional(v.string()),
    \\  contains: v.optional(v.array(Base58Schema)),
    \\  'derived-from': v.optional(v.array(Base58Schema)),
    \\  guild: v.optional(v.array(Base58Schema)),
    \\  signatures: v.optional(v.array(SignatureSchema))
    \\};
    \\
    \\/** v1 legacy shape — `jelly.dreamball` with no subtype suffix. */
    \\export const DreamBallUntypedSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball'),
    \\  look: v.optional(LookSchema),
    \\  feel: v.optional(FeelSchema),
    \\  act: v.optional(ActSchema)
    \\});
    \\
    \\export const DreamBallAvatarSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball.avatar'),
    \\  look: v.optional(LookSchema),
    \\  feel: v.optional(FeelSchema)
    \\});
    \\
    \\export const DreamBallAgentSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball.agent'),
    \\  look: v.optional(LookSchema),
    \\  feel: v.optional(FeelSchema),
    \\  act: v.optional(ActSchema),
    \\  memory: v.optional(MemorySchema),
    \\  'knowledge-graph': v.optional(KnowledgeGraphSchema),
    \\  'emotional-register': v.optional(EmotionalRegisterSchema),
    \\  'interaction-set': v.optional(v.array(InteractionSetSchema)),
    \\  'personality-master-prompt': v.optional(v.string()),
    \\  secret: v.optional(v.array(SecretRefSchema))
    \\});
    \\
    \\export const DreamBallToolSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball.tool'),
    \\  skill: v.optional(SkillSchema),
    \\  'applicable-to': v.optional(v.array(v.string()))
    \\});
    \\
    \\export const DreamBallRelicSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball.relic'),
    \\  'sealed-payload-hash': Base58Schema,
    \\  'unlock-guild': Base58Schema,
    \\  'reveal-hint': v.optional(v.string()),
    \\  'sealed-until': v.optional(Rfc3339Schema)
    \\});
    \\
    \\export const DreamBallFieldSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball.field'),
    \\  'omnispherical-grid': v.optional(OmnisphericalGridSchema),
    \\  'ambient-palette': v.optional(v.array(v.string())),
    \\  'dream-field-id': v.optional(v.string())
    \\});
    \\
    \\export const DreamBallGuildSchema = v.object({
    \\  ...commonCore,
    \\  type: v.literal('jelly.dreamball.guild'),
    \\  'guild-name': v.optional(v.string()),
    \\  'keyspace-root-hash': v.optional(Base58Schema),
    \\  member: v.optional(v.array(Base58Schema)),
    \\  admin: v.optional(v.array(Base58Schema)),
    \\  policy: v.optional(GuildPolicySchema)
    \\});
    \\
    \\/** Top-level DreamBall — discriminated on `type`. Use this to
    \\ *  validate any incoming .jelly JSON. */
    \\export const DreamBallSchema = v.variant('type', [
    \\  DreamBallUntypedSchema,
    \\  DreamBallAvatarSchema,
    \\  DreamBallAgentSchema,
    \\  DreamBallToolSchema,
    \\  DreamBallRelicSchema,
    \\  DreamBallFieldSchema,
    \\  DreamBallGuildSchema
    \\]);
    \\
    \\export type DreamBallValidated = InferOutput<typeof DreamBallSchema>;
    \\
    \\// ========================================================================
    \\// Convenience — safeParse returning a discriminated result.
    \\// ========================================================================
    \\
    \\export type ParseResult<T> =
    \\  | { success: true; data: T }
    \\  | { success: false; issues: v.BaseIssue<unknown>[] };
    \\
    \\/** Parse a JSON string to a validated DreamBall. Throws on invalid. */
    \\export function parseDreamBall(jsonText: string): DreamBallValidated {
    \\  const parsed = JSON.parse(jsonText);
    \\  return v.parse(DreamBallSchema, parsed);
    \\}
    \\
    \\/** Same as parseDreamBall but returns a tagged result. */
    \\export function safeParseDreamBall(jsonText: string): ParseResult<DreamBallValidated> {
    \\  let raw: unknown;
    \\  try {
    \\    raw = JSON.parse(jsonText);
    \\  } catch (e) {
    \\    return {
    \\      success: false,
    \\      issues: [
    \\        {
    \\          kind: 'schema',
    \\          type: 'json',
    \\          input: jsonText,
    \\          expected: 'valid JSON',
    \\          received: (e as Error).message,
    \\          message: `invalid JSON: ${(e as Error).message}`,
    \\          requirement: undefined,
    \\          path: undefined,
    \\          issues: undefined,
    \\          lang: 'en',
    \\          abortEarly: undefined,
    \\          abortPipeEarly: undefined
    \\        } as v.BaseIssue<unknown>
    \\      ]
    \\    };
    \\  }
    \\  const result = v.safeParse(DreamBallSchema, raw);
    \\  if (result.success) return { success: true, data: result.output };
    \\  return { success: false, issues: result.issues };
    \\}
    \\
    \\// ========================================================================
    \\// §13 palace envelope Valibot schemas
    \\// ========================================================================
    \\
    \\export const PlacementSchema = v.object({
    \\  'child-fp': Base58Schema,
    \\  position: v.tuple([v.number(), v.number(), v.number()]),
    \\  facing: v.tuple([v.number(), v.number(), v.number(), v.number()])
    \\});
    \\
    \\export const LayoutSchema = v.object({
    \\  type: v.literal('jelly.layout'),
    \\  'format-version': v.literal(2),
    \\  placements: v.array(PlacementSchema),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const ActionKindSchema = v.picklist([
    \\  'palace-minted',
    \\  'room-added',
    \\  'avatar-inscribed',
    \\  'aqueduct-created',
    \\  'move',
    \\  'true-naming',
    \\  'inscription-updated',
    \\  'inscription-orphaned',
    \\  'inscription-pending-embedding'
    \\]);
    \\
    \\export const TimelineSchema = v.object({
    \\  type: v.literal('jelly.timeline'),
    \\  'format-version': v.literal(3),
    \\  'palace-fp': Base58Schema,
    \\  'head-hashes': v.array(Base58Schema),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const ActionSchema = v.object({
    \\  type: v.literal('jelly.action'),
    \\  'format-version': v.literal(3),
    \\  'action-kind': ActionKindSchema,
    \\  actor: Base58Schema,
    \\  'parent-hashes': v.array(Base58Schema),
    \\  'target-fp': v.optional(Base58Schema),
    \\  timestamp: v.optional(v.number()),
    \\  deps: v.optional(v.array(Base58Schema)),
    \\  nacks: v.optional(v.array(Base58Schema))
    \\});
    \\
    \\export const AqueductPhaseSchema = v.picklist(['in', 'out', 'standing', 'resonant']);
    \\
    \\export const AqueductSchema = v.object({
    \\  type: v.literal('jelly.aqueduct'),
    \\  'format-version': v.literal(2),
    \\  from: Base58Schema,
    \\  to: Base58Schema,
    \\  kind: v.string(),
    \\  capacity: v.number(),
    \\  strength: v.number(),
    \\  resistance: v.number(),
    \\  capacitance: v.number(),
    \\  conductance: v.optional(v.number()),
    \\  phase: v.optional(AqueductPhaseSchema),
    \\  'last-traversed': v.optional(v.number())
    \\});
    \\
    \\export const ElementTagSchema = v.object({
    \\  type: v.literal('jelly.element-tag'),
    \\  'format-version': v.literal(2),
    \\  element: v.string(),
    \\  phase: v.optional(v.string()),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const TrustAxisSchema = v.object({
    \\  name: v.string(),
    \\  value: v.number(),
    \\  range: v.tuple([v.number(), v.number()])
    \\});
    \\
    \\export const TrustObservationSchema = v.object({
    \\  type: v.literal('jelly.trust-observation'),
    \\  'format-version': v.literal(2),
    \\  observer: Base58Schema,
    \\  about: Base58Schema,
    \\  axes: v.optional(v.array(TrustAxisSchema)),
    \\  'observed-at': v.optional(v.number()),
    \\  context: v.optional(v.string()),
    \\  signatures: v.optional(v.array(SignatureSchema))
    \\});
    \\
    \\export const InscriptionSchema = v.object({
    \\  type: v.literal('jelly.inscription'),
    \\  'format-version': v.literal(2),
    \\  surface: v.string(),
    \\  placement: v.string(),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\export const MythosSchema = v.object({
    \\  type: v.literal('jelly.mythos'),
    \\  'format-version': v.literal(2),
    \\  'is-genesis': v.boolean(),
    \\  predecessor: v.optional(Base58Schema),
    \\  about: v.optional(Base58Schema),
    \\  form: v.optional(v.string()),
    \\  body: v.optional(v.string()),
    \\  'true-name': v.optional(v.string()),
    \\  'discovered-in': v.optional(Base58Schema),
    \\  synthesizes: v.optional(v.array(Base58Schema)),
    \\  'inspired-by': v.optional(v.array(Base58Schema)),
    \\  author: v.optional(Base58Schema),
    \\  'authored-at': v.optional(v.number())
    \\});
    \\
    \\export const ArchiformSchema = v.object({
    \\  type: v.literal('jelly.archiform'),
    \\  'format-version': v.literal(2),
    \\  form: v.string(),
    \\  tradition: v.optional(v.string()),
    \\  'parent-form': v.optional(v.string()),
    \\  note: v.optional(v.string())
    \\});
    \\
    \\// DO NOT EDIT — generated by tools/schema-gen/main.zig
    \\
;

pub fn main() !void {
    var gpa_state: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa_state.deinit();
    const gpa = gpa_state.allocator();

    const io = std.Io.Threaded.global_single_threaded.io();

    // Ensure src/lib/generated/ exists.
    std.Io.Dir.cwd().createDirPath(io, "src/lib/generated") catch |e| switch (e) {
        error.PathAlreadyExists => {},
        else => return e,
    };

    try writeFile(TYPES_OUT, TYPES_SRC);
    try writeFile(CBOR_OUT, CBOR_SRC);
    try writeFile(SCHEMAS_OUT, SCHEMAS_SRC);
    try writeFile(README_OUT, README_SRC);

    _ = gpa;
    const stdout = std.Io.File.stdout();
    var buf: [256]u8 = undefined;
    var w = stdout.writer(io, &buf);
    try w.interface.print(
        "schema-gen wrote: {s}, {s}, {s}, {s}\n",
        .{ TYPES_OUT, CBOR_OUT, SCHEMAS_OUT, README_OUT },
    );
    try w.interface.flush();
}

fn writeFile(path: []const u8, contents: []const u8) !void {
    const io = std.Io.Threaded.global_single_threaded.io();
    var file = try std.Io.Dir.cwd().createFile(io, path, .{ .truncate = true });
    defer file.close(io);
    var buf: [4096]u8 = undefined;
    var w = file.writer(io, &buf);
    try w.interface.writeAll(contents);
    try w.interface.flush();
}
